bids-standard/pybids

- bids/grabbids/README.md
- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/tests/test_grabbids.py
- setup.py
Closes #16.
I also added get_subjects().
> get_fieldmap()

- bids/grabbids/config/bids.json
"extension" from grabbit should be used instead
> Remove "ext"

- bids/grabbids/README.md
- bids/grabbids/config/bids.json
- bids/grabbids/tests/test_grabbids.py
otherwise just minor things ;)
> BF: regex for run to not include run- prefix

- bids/grabbids/config/bids.json
> added 'dir' and 'acq' filename keys

- bids/events/base.py
- bids/events/tests/test_base.py
- requirements.txt
Close #47 
If `condition_column` (by default trial_type) is not found, warn instead of error, and set `condition_column` to None,
> Warn if trial_type column not found, set to None

- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/tests/test_grabbids.py
- added DWI file stubs to ds005 demo
- fixed crash in get_nearest_helper when no entries found
- fixed bval/bvec getters
- added test for bval/bvec getters
> CRN Sprint Fixes

- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/tests/test_grabbids.py
- Added support for including and excluding top level directories in config.json (new grabbit feature), instead of using the `exclude_dir` parameter. By default, only subject directories are indexed. 
- Added test in which files under `models` are ignored
- Require all files with subject entities to be under a subject folder (and added test with invalid file)
- add underscore to `get_nearest_helper` (internal function)
- `find_match` is made obsolete by `get_nearest`, removed.
> Minor improvements

- .travis.yml
- bids/grabbids/bids_layout.py
- bids/grabbids/bids_validator.py
- bids/grabbids/tests/test_grabbids.py
- bids/grabbids/tests/test_validator.py
General cleanup, docstring addition, and PEP8 fixes. Also makes sure the `BIDSLayout` initializer passes the `index_associated` argument to `BIDSValidator`, addressing the issue raised in #72.
> cleanup and PEP8; passes index_associated to validator; fixes #72

- .travis.yml
- bids/grabbids/config/bids.json
- doc/index.rst
Adds echo entity for json for grabbing single echos from multi-echo
data. Useful for cases where we would compare single / multi-echo
data in the same processing stream.
> Add echo to json

- bids/grabbids/bids_layout.py
> [FIX] Fieldmaps - make magnitude2 optional

- .travis.yml
- appveyor.yml
- bids/__init__.py
- bids/analysis/base.py
- bids/analysis/variables.py
- bids/grabbids/bids_layout.py
- bids/grabbids/config/derivatives.json
- bids/grabbids/tests/test_grabbids.py
- bids/version.py
- setup.py
This is a running list of suggestions for the analysis module, to facilitate discussion.
Feel free to merge or cherry-pick useful commits. I will rebase on the latest HEAD of the branch at intervals.
> [WIP] Suggestions for and discussion of analysis module

- .travis.yml
- bids/grabbids/bids_layout.py
- bids/grabbids/tests/test_grabbids.py
I'm sitting in @mih's kitchen and he made me add this at knifepoint
> add entities to get_metadata

- bids/grabbids/config/bids.json
> [WIP] ENH: Add default_path_patterns to bids.json

- CHANGELOG.md
- bids/version.py
This updates the changelog and version in preparation for the 0.5.0 release. I'm waiting on one or two other PRs before pulling the trigger.
> Version bump

- CHANGELOG.md
- bids/version.py
Hotfix release. If anybody needs anything in before, speak up now. Merging and releasing on passing Travis.
> REL: 0.5.1

- bids/grabbids/bids_layout.py
Adds a little repr method to the `BIDSLayout` class. Feel free to give comments on whether the subjects/sessions/runs fields are the right ones to treat in a special way here...
> bidslayout repr

- bids/analysis/analysis.py
To fix minor issue on #147 - last comment
> Removed un-unused args from Analysis init

- bids/analysis/analysis.py
- bids/analysis/auto_model.py
- bids/analysis/transformations/munge.py
> Misc fixes/enhancements to analysis-module

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/base.py
> set default transformation groupby value to None

- bids/variables/io.py
- bids/variables/tests/test_io.py
> Apply regex to TSV variable loading

- README.md
Hi @tyarkoni 
Here's our update as requested in #221 - hope it makes sense 🍨
> Fix link in README to point to documentation

- README.md
> DOC: Punctuation should not be part of link

- README.md
> DOC: Punctuation should not be part of link 2

- bids/layout/validation.py
- bids/version.py
> Add validator json to PACKAGE_DATA

- bids/variables/kollekshuns.py
Added more meaningful information/error messages to crashes within definition of var_levels. 
(cc @yarikoptic)
> ENH: add more meaningful error messages for var_levels ingestion

- bids/analysis/analysis.py
- bids/analysis/hrf.py
- bids/analysis/tests/test_analysis.py
- bids/analysis/transformations/compute.py
> Fix issues with sparse Convolved variables

- bids/layout/layout.py
Fixes #293 and some other unclosed json `load`s.
> [FIX] File object not closed for ``dataset_description.json``

- bids/analysis/analysis.py
- bids/config.py
> FIX: Load JSON files using context managers

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
> FIX: Propagate derivative entities into top-level dynamic getters

- bids/analysis/analysis.py
- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/compute.py
- bids/analysis/transformations/munge.py
- bids/variables/io.py
- bids/variables/kollekshuns.py
- bids/variables/variables.py
> sort=True for pd.concat

- .mailmap
- .zenodo.json
- tools/prep_zenodo.py
> MAINT: Add .zenodo.json

- bids/analysis/transformations/munge.py
- bids/variables/kollekshuns.py
- bids/variables/variables.py
> fix bugs in entity-setting and Rename transformation

- bids/analysis/analysis.py
- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/__init__.py
- bids/analysis/transformations/munge.py
- bids/variables/variables.py
Adds a DropNA transformation, per the draft specification. This simply drops all rows with missing values from the named variable(s).
> Adds DropNA transformation

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Closes #288; see also discussion in #124.
> Add get_tr() method to BIDSLayout

- CHANGELOG.md
- bids/layout/config/bids.json
- bids/layout/layout.py
- examples/pybids tutorial.ipynb
This updates the changelog to reflect everything that's happened since 0.6.5. Once merged, I think we're ready to release 0.7.0.
> Version bump --> 0.7.0

- bids/tests/utils.py
Should fix the tests.
Closes #345.
> FIX: Get the absolute path of the test data directory

- bids/variables/variables.py
Just a tiny change in names (`sr` --> `time_freq`) to make it a bit more obvious what is happening here.
> ENH: minor renaming to improve intuitive understanding

- .travis.yml
This is making glancing over issues hard.
> CI: Ignore OSX Python 3.5 failures

- .zenodo.json
- CHANGELOG.md
- tools/update_changes.sh
We've had a burst of fixes lately, and I think it would be good to go ahead and have another release before #369.
Pending merge or postponement decision on:
I'm going to start a 0.7.1 milestone. Please tag your PRs with that milestone iff you want to block release on their merge. If you are okay with postponing to 0.7.2 or 0.8.0, just go ahead and check the box above.
> REL: 0.7.1

- bids/layout/README.md
- bids/layout/config/bids.json
- bids/layout/core.py
- bids/layout/layout.py
- bids/layout/tests/test_core.py
> FIX: broken paths on Windows

- paper/paper.bib
- paper/paper.md
Adds files needed for submission to [JOSS](http://joss.theoj.org) (see #394). All: please look over `paper.md` and feel free to provide comments/edits. Keep in mind that this is meant to be "a summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience" (see [author guidelines](https://joss.readthedocs.io/en/latest/submitting.html)); it is *not* a tutorial on how to use the software. It's supposed to be 250 - 1,000 words (we're currently around 600).
I'll give this a few days, then will probably submit early next week. Please provide comments before then.
> preparation for JOSS submission

- paper/paper.md
Addresses https://github.com/openjournals/joss-reviews/issues/1289#issuecomment-468429502.
> JOSS submission fixes

- bids/due.py
Originally mentioned in https://github.com/bids-standard/pybids/issues/245 .
> BF: 0.0.7 version of duecredit stub, addresses import issue check on py3

- bids/reports/report.py
Adds rationale for why a Counter is useful for the output.
> Update docstring for BIDSReport

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
> Derivative indexing documentation

- paper/paper.md
Integrates minor changes to author list based on the [JOSS review thread](https://github.com/openjournals/joss-reviews/issues/1294).
> JOSS review-related changes

- bids/version.py
Builds sdist and wheel and runs `twine check`.
> FIX: CI deployment

- .mailmap
- .zenodo.json
- tools/prep_zenodo.py
We might need a 0.9.1 release, so I figured I'd update the Zenodo.
Closes #387.
> MAINT: Update zenodo

- bids/layout/layout.py
- bids/variables/tests/test_variables.py
While going through the codebase, I took the liberty to make the code pep8 compliant wherever there was a straightforward solution.
PS: https://github.com/bids-standard/pybids/pull/456/commits/7f33b5cae346d36cd7c0f841c8545bacc108fa19 is not pep8 related: It simply fixes a typo in the docstring
PPS: slightly related to #136 #401
> PEP8 Fixes

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Starting with a test showing that we don't have it.
@tyarkoni Is this easy? I haven't dug into SQLAlchemy in a long time.
> FIX: Restore <entity>=None query returning files lacking the entity

- .zenodo.json
- CHANGELOG.md
I plan to release in the morning.
@cmadjar Sure you don't want to add yourself to the Zenodo?
> REL: 0.9.2

- .travis.yml
> CI: Execute notebook in Travis

- bids/reports/parsing.py
- bids/reports/report.py
- bids/reports/tests/test_parsing.py
- bids/reports/utils.py
- changes all extension='.nii.gz' to extention=[".nii", ".nii.gz"]
- add missing import os in report/util.py
> make bids.reports deal .nii only BIDS dataset

- .zenodo.json
- CHANGELOG.md
Minor release prompted mainly by #468. See Changelog for details.
> REL: 0.9.3

- .travis.yml
- bids/layout/config/bids.json
Also updated the path pattern. @tyarkoni Do you want to validate that pattern? Or do we have tests to make sure each pattern produces expected results?
Fixes #476.
> FIX: Drop bold suffix constraint from echo entity

- README.md
Badges are starting to clutter, so I put the citeable stuff on one line, and the rest on another.
Ref:
* https://github.com/openjournals/joss-reviews/issues/1294
* https://github.com/openjournals/joss-papers/pull/897
> DOC: Add JOSS Badge

- examples/pybids_tutorial.ipynb
Apply syntax highlight to Python notebook example doc.
> STYLE: Apply syntax highlight to Python notebook example doc

- examples/pybids_tutorial.ipynb
Finish sentence in Python Notebook example documentation.
> DOC: Finish sentence in Python Notebook example documentation

- examples/pybids_tutorial.ipynb
Improve wording in Python notebook example comment.
> DOC: Improve wording in Python notebook example comment

- .mailmap
- .zenodo.json
- CHANGELOG.md
- tools/prep_zenodo.py
Preparation for 0.9.4 release. Should be able to do this today, depending on my wifi situation on Amtrak.
@jhlegarreta Do you want to add your information (preferred name style on publications, affiliation, [ORCID](https://orcid.org/)) to the `.zenodo.json`? You can comment here or open a PR against the `rel/0.9.4` branch.
@cmadjar I've added you to a blacklist so that we don't keep bugging you about being added as an author. Please let us know if you change your mind.
Closes #504.
> REL: 0.9.4

- bids/layout/__init__.py
- bids/layout/index.py
- bids/layout/layout.py
Isolating the least controversial changes into a separate PR.  Trying to take smaller steps forward.
> Simple code analysis

- bids/variables/entities.py
Change from 'Node' to 'object' for inheritance.
> RF: Subclass analysis Node from object

- bids/__init__.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/writing.py
Address several issues identified by doing code analysis.
> STY: General cleanups

- .mailmap
- .zenodo.json
- CHANGELOG.md
Preparation for 0.9.5 release, which will be the last with any pretense of Python 2 support.
@hjmjohnson @satra @ashgillman I took your Zenodo entries from the nipype Zenodo file. Please let me know if you would rather not be listed as authors.
> REL: 0.9.5

- .circleci/config.yml
- setup.cfg
* Adds a `dev` extra so it's quicker to set up a dev environment. (It's just doc + test.)
* First pass CircleCI to begin addressing #502. This will need to be merged and Circle activated before we can mark that one closed, though.
> MNT: Various

- .circleci/artifact_path
> CI: Configure Circle Artifact Redirector

- bids/layout/__init__.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
> Adds support for NONE and ANY query Enums

- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/reports/report.py
Miscellaneous PEP8 fixes that were annoying me.
> Minor PEP8 Fixes

- .zenodo.json
- CHANGELOG.md
Preparation for 0.10.0 release. Will wait for tests to pass and merge, barring an objection.
Release process documented in https://github.com/bids-standard/pybids/wiki/Release-Process
> REL: 0.10.0

- .gitignore
- .zenodo.json
Would you mind adding .vscode to the .gitignore for Visual Studio Code users like myself?
> ENH: Add .vscode (for Visual Studio Code) to .gitignore

- .zenodo.json
thanks to @effigies for pointing this out.
> add institution/orcid to zenodo for jdkent

- CHANGELOG.md
> REL: 0.10.2

- .mailmap
- .zenodo.json
- CHANGELOG.rst
Preparation for 0.11.0 series.
@adam2392 @kalenkovich I have added you as authors for the Zenodo archive. If you would like different names/spellings, to add affiliation and ORCID, or to decline to be listed as authors, please let me know ASAP.
> REL: 0.11.0

- .mailmap
- .zenodo.json
- CHANGELOG.rst
Preparation for 0.12.1 release.
@suganya-sk I have added you as an author for the Zenodo archive. If you would like a different name/spelling, to add affiliation and ORCID, or to decline to be listed as an author, please let me know ASAP.
> REL: 0.12.1

- bids/layout/index.py
> Force utf-8 encoding in _index_metadata

- bids/variables/io.py
> FIX: Support nibabel < 3 when calculating time series length

- .zenodo.json
- CHANGELOG.rst
Preparation for 0.12.2 release, fixing a few small bugs.'
@36000 I have added you as an author for the Zenodo archive. If you would like a different name/spelling, to add affiliation and ORCID, or to decline to be listed as an author, please let me know ASAP.
> REL: 0.12.2

- CHANGELOG.rst
- Preparation for 0.12.3 release
> REL: 0.12.3

- bids/layout/tests/test_layout.py
- bids/layout/validation.py
closes #704
- add error message indicating which file was not read correctly
- add test confirming the error message is raised
> add more informative validation error message for dataset_description.json

- bids/layout/layout.py
- bids/modeling/hrf.py
- bids/modeling/transformations/base.py
Just a bit of clutter, unrelated to other efforts.
> FIX: Clean up some deprecation and syntax warnings

- bids/modeling/statsmodels.py
- bids/tests/data/ds005/models/ds-005_type-test_model.json
> RF: Remove group_by from edges and add filter

- bids/modeling/model_spec.py
Using GLMMSpec alias as a stand-in for now. Probably can just pare it down, but I don't understand GLMMSpec enough yet to know what to cut out.
Closes #726.
> ENH: Add meta-analysis model type

- bids/modeling/statsmodels.py
- bids/tests/data/ds005/models/ds-005_type-test_model.json
Starting with a test...
Closes #741.
> ENH: Permit explicit intercept (1) in Contrasts and DummyContrasts

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- setup.cfg
- tools/ci/install_dependencies.sh
> [ENH] Add visualization for statsmodel graph

- bids/modeling/statsmodels.py
- bids/modeling/transformations/base.py
Not easily separable from #733, so targeting that branch.
Closes #736.
> ENH: Use indirect transformations structure

- bids/variables/io.py
Functional derivatives draft compatibility.
> ENH: Accept variables from timeseries as well as regressors

- bids/modeling/statsmodels.py
cc: @effigies 
Fixes https://github.com/bids-standard/pybids/issues/754
> FIX: AttributeError bug in statsmodel.py

- bids/modeling/tests/test_transformations.py
- bids/modeling/transformations/__init__.py
- bids/modeling/transformations/compute.py
Closes #758.
Tests coming tomorrow.
> ENH: Add Lag transformation

- bids/config.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/layout/tests/test_utils.py
- bids/tests/test_config.py
- bids/variables/tests/test_io.py
Follow up to #629, in preparation for a 0.14 release.
> MNT: Disable bids-nodot mode

- bids/layout/tests/data/sample_validation_config.json
- bids/layout/validation.py
- bids/modeling/model_spec.py
- bids/modeling/statsmodels.py
- bids/variables/tests/test_collections.py
- bids/variables/variables.py
- doc/sphinxext/github.py
- doc/sphinxext/math_dollar.py
- pyproject.toml
- tools/ci/install_dependencies.sh
* Remove trailing spaces at end of line.
* Remove empty lines at end of file.
> Remove trailing spaces

- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/tests/bids_specs.json
- bids/tests/bids_specs_with_oligarchy.json
> FIX: Accept paths/strings for layout configuration files

- bids/__main__.py
This will help with debugging, as you can then do something like `python -m pdb -m bids`.
> ENH: Add __main__ to allow `python -m bids` to run CLI

- bids/layout/validation.py
Apologies for the drive-by commit, but I was troubleshooting a BIDSLayout with derivatives indexing and saw this enough to get motivated to PR.
> quick text only update

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
Fixes #795.
I can't easily see a good way to test this with our current testing infrastructure, so I think it'll need to wait.
> ENH: Handle wildcards in model X

- bids/variables/entities.py
> MNT: Replace deprecated DataFrame.append call

- bids/cli.py
- setup.cfg
Recent click has deprecated our use case, but I think we actually hadn't implemented it correctly anyway.
> FIX:Allow ``pybids layout --derivatives`` to be a boolean flag or accept a path

- .mailmap
- .zenodo.json
- CHANGELOG.rst
- tools/prep_zenodo.py
- tools/update_changes.sh
Looked at the git log, and we could stand a release. Targeting Monday so we don't cause issues over the weekend.
Would be good to look through the log and see if there are bug-fixes worth getting in before then, but everybody's time is limited and we shouldn't hold this up aspirationally.
@jmumford I've added your info to the Zenodo. Please let me know if it's all correct or if you'd rather not be listed.
> REL: 0.15.2

- bids/modeling/tests/test_transformations.py
- bids/modeling/transformations/base.py
- bids/modeling/transformations/compute.py
sync_kwargs needs to be false for:
- convolve
- logical operators
- Orthogonalize
- Product
- Split
- Sum
> [FIX,TEST] sync_kwargs

- .github/workflows/docs.yml
- .github/workflows/package.yml
- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
Small thing noticed while looking at #896 logs.
> CI: Update actions versions

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- bids/layout/layout.py
- bids/modeling/statsmodels.py
Fixes failure in pre-release checks.
> FIX: Use kwargs for DataFrame.pivot()

- README.md
> DOC: Mention conda installation in README

- bids/layout/config/bids.json
- add T2startw and PD suffixes to anat filename patterns
- add run and task entity to anat filename patterns
- remove duplicates between parametric and non parametric anat suffixes
> Update default anat filename patterns in config

- README.md
> Fix tutorial link in README

- bids/layout/layout.py
I hope the fix is correct, please double-check.
> MNT: fix repeat-word typo

- bids/due.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_path_building.py
- bids/modeling/model_spec.py
- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- bids/modeling/tests/test_transformations.py
- bids/modeling/transformations/base.py
- bids/reports/parameters.py
- bids/reports/report.py
- bids/variables/collections.py
- bids/variables/entities.py
- bids/variables/tests/test_collections.py
- bids/variables/variables.py
- doc/sphinxext/docscrape.py
- doc/sphinxext/numpydoc.py
- pyproject.toml
Add **`Python :: 3`** or **`Python :: 3 :: Only`** in classifiers?
> MNT: a few Python3 updates

- .zenodo.json
- CHANGELOG.rst
Looking at the changelog, it seems a feature release is worth making. It's been a year, and the refactoring of derivatives is a potential source of (hopefully very minor) breakage.
> REL: 0.16.0

- .github/workflows/stable.yml
> CI: Update Python version for doc/sdist/wheel tests

- bids/layout/config/bids.json
- bids/layout/tests/test_utils.py
> FIX: Improve parsing of suffix/extension in non-BIDS files

- doc/sphinxext/docscrape.py
- doc/sphinxext/docscrape_sphinx.py
- doc/sphinxext/numpydoc.py
Address a class of issues reported by ruff.
> MNT, DOC: fix imports in documentation scripts

- bids/layout/validation.py
Print path to file that raises the error message
Fixes #1022
> Clearer BIDSValidation error message

- bids/layout/tests/test_layout_on_examples.py
quick PR before I forget
relates to https://github.com/bids-standard/pybids/pull/1059#issuecomment-2094675508
> [MAINT] add tests to cover ieeg, eeg, dwi

- bids/layout/config/bids.json
Preparation for BEP22 merge. I think pybids can lead BIDS a little here.
> ENH: Add MRS entities, path patterns

- .zenodo.json
- CHANGELOG.rst
#1074 justifies a minor release bump. Will release on Monday, and we'll see if bug reports start rolling in.
> REL: 0.17.0

- .zenodo.json
- CHANGELOG.rst
- doc/examples/pybids_tutorial.md
- pyproject.toml
Consolidating some recent fixes and improvements.
> REL: 0.19.0

- doc/examples/pybids_tutorial.md
Small PR - Commit 81a6467fc01a028ca6e3d77e96f52f38a3819665 moved `derivatives.json`. This PR adjusts sources to changes.
> Update derivatives config file
