- bids/grabbids/README.md
The 'sub-' prefix is already inserted by the config, so including it in the query breaks it. Took me a while to work this out. Hopefully saves someone else a few minutes of confusion.
By the way, there is a very similar version of this repo at https://github.com/INCF/grabbit. Let me know if I should be working with that one instead.
> fix broken example in documentation

- bids/grabbids/bids_layout.py
A new option was added to grabbit classes. In order to expose these to packages using pybids having the init of BIDSLayout take kwargs and then pass them on in the super call to the grabbit Layout class is necessary.
> Add kwargs to BIDSLayout init

- .travis.yml
- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/tests/test_grabbids.py
- bids/version.py
This replaces much of the code in `get_metadata()` with a cleaner approach that leverages the latest version of grabbit. Also provides a generic `get_nearest()` method that can be easily used to walk up the hierarchy and get the appropriate file for any given input file. E.g.,
```python
layout = BIDSLayout(path)
event_file = layout.get_nearest('path/to/sub-03_ses-1_run-1_bold.nii.gz', type='event', all_=True)
```
...would return all matching event files in the hierarchy for the given functional.
> adds get_nearest() functionality via new grabbit version

- bids/grabbids/bids_layout.py
To avoid breaking the API I added a new function `get_fieldmaps` that always returns a list (in contrast to `get_fieldmap` which returns a single fieldmap if there is only one present).
> [RTM] account for the situation where multiple fieldmaps are present

- bids/grabbids/bids_layout.py
`os.path.realpath` dereferences symlinks, which will almost always destroy the naming structure required by BIDS. `git-annex`-managed datasets, such as those obtained through datalad, cannot be used in indirect mode and still work with pybids.
`os.path.abspath` puts paths into a normal form, without potentially rewriting paths outside the BIDS directory.
Are there any reasons to use `realpath` that I'm missing?
> ENH: Use abspath instead of realpath

- bids/grabbids/config/bids.json
Fixes breaking tests on Windows. The problem was that the forward slash was hardcoded as the path separator in the JSON config file.
> OS-compatible path sep; fixes breaking windows tests

- .travis.yml
- appveyor.yml
- bids/grabbids/bids_layout.py
Forces utf-8 encoding when reading JSON file contents. This will address problems on platforms where utf-8 is not the default encoding. This shouldn't cause anyone problems unless they're already in violation of the BIDS spec, as JSON files are supposed to always be UTF-8 encoded.
> forces utf-8 encoding; fixes #70

- bids/grabbids/bids_layout.py
When I query a file that grabbit has nothing to say about, I get an error that can be mistaken for "there is no such file". Maybe one could phrase it like:
"File '%s' does not match any specification in the current BIDS project."
```
l=BIDSLayout('.')
l.get_metadata('participants.tsv')
--------------------------------------------------------------------------
ValueError                               Traceback (most recent call last)
<ipython-input-35-81dce41d2921> in <module>()
----> 1 l.get_metadata('participants.tsv')
/home/mih/.local/lib/python2.7/site-packages/bids/grabbids/bids_layout.pyc in get_metadata(self, path, **kwargs)
43     def get_metadata(self, path, **kwargs):
44 
---> 45         potentialJSONs = self.get_nearest_helper(path, '.json', **kwargs)
46 
47 …
```
> Somewhat misleading error message by BIDSLayout.get_metadata()

- .travis.yml
- appveyor.yml
- bids/grabbids/bids_layout.py
```
/home/mih/.local/lib/python2.7/site-packages/bids/grabbids/bids_layout.pyc in get_metadata(self, path, **kwargs)
83             if os.path.exists(json_file_path):
84                 param_dict = json.load(open(json_file_path, "r",
---> 85                                             encoding='utf-8'))
86                 merged_param_dict.update(param_dict)
87 
TypeError: 'encoding' is an invalid keyword argument for this function
```
I am aware that there is no upstream interest in PY2. Please advice on possible ways to be able to keep building on pybids for applications that need PY2 compatibility.
> Restore PY2 compat

- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/config/derivatives.json
- bids/grabbids/tests/test_grabbids.py
In order to effectively select outputs of fmriprep (and, presumably, other derivatives-producing programs), the following entries in `bids.json` are required: `target`, `space`, `class`, `variant`.
> ENH: Derivative entities

- bids/grabbids/config/bids.json
Here is the demo
```
In [1]: from bids.grabbids import BIDSLayout
In [2]: l=BIDSLayout('.')
In [3]: l.get_metadata('sub-03/ses-localizer/func/sub-03_ses-localizer_task-retmapccw_run-
...: 1_recording-cardresp_physio.tsv.gz')
Out[3]: 
{u'CogAtlasID': u'http://www.cognitiveatlas.org/term/id/trm_558c4d3105abf',
u'TaskDescription': u'Participants fixate the center of the screen while a counter-clockwise rotating wedge (not a properlor) stimulus is being displayed.',
u'TaskName': u'retmapccw'}
In [4]: cat recording-cardresp_physio.json
{
"SamplingFrequency": 500.0, 
"StartTime": 0.0, 
"Columns": [
"trigger", 
"cardiac", 
"respiratory"
], 
"ContentDescription": "Activity recorded with a pulse oximeter (cardiac) and respiration belt."
}
```
I think the name and location of the file is legit (I …
> Legit side car files for 'recording's are ignored

- bids/grabbids/bids_layout.py
To work with `_get_nearest_helper`, files have to have a defined `type`. Currently invalid files produce an uninformative `KeyError`; this returns a more informative message.
> more informative failure in get_nearest_helper; fixes #82

- setup.py
Otherwise `derivatives.json` doesn't get installed
> FIX: install all json files under config during setup

- bids/analysis/tests/test_base.py
- bids/analysis/tests/test_transformations.py
- bids/analysis/tests/test_variables.py
- bids/analysis/transform/base.py
- bids/analysis/transform/munge.py
- bids/analysis/variables.py
This PR allows individual `DenseEventColumn`s to have different sampling rates. This means we no longer have to resample all temporal variables to a common sampling rate when they're first read in. Instead, resampling can be deferred until it can't be avoided (and, in the case of variables that natively have the same sampling rate as the eventual output sampling rate, no resampling needs to be performed at all).
> Column sampling rate

- bids/grabbids/config/bids.json
We had a duplicate of `acq` and `acquisition`. Talking with @tyarkoni and @chrisfilo, we decided we should support both, but use aliases (grabbles/grabbit#39) to reduce duplication. Further, it was decided the entity short name (e.g. "ses" for "session") should be available for users, so aliases were added for all such entities.
The remaining unimplemented entities ("ce", "rec" and "mod") were added, and reordered to keep the standard entities together.
> ENH: Include all entities in bids.json

- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
Pulls three fixes out of #110:
* Path patterns are updated to make task required and include .nii.gz extensions
* Parsing patterns require that the entity key be preceded with `_` or `/`, to avoid conflicts when one entity is the suffix of another (e.g., `ce` and `space` from the derivatives extension).
* Allows extensions to be valid filenames, which permits downstream software to package their own extensions
Does not update path patterns to condition entity values, as that's unreleased grabbit behavior at present.
> Grabbids updates: Path patterns, regex matches, custom extensions

- bids/grabbids/bids_layout.py
In order to flexibly create new filenames from source files, I parse the source files to get the original entities, make some modifications to the entity dictionary, and then use `build_path` to get the new filename.
If this seems like a useful thing to have in pybids, it could probably fit fairly naturally in a number of places, and this proposal is just one of them. Let me know what you think.
> ENH: Parse entities without adding to layout

- bids/analysis/analysis.py
- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/__init__.py
- bids/analysis/transformations/base.py
- bids/analysis/transformations/compute.py
- bids/analysis/transformations/munge.py
Addresses #127.
Currently modifying input models to use `"and_"` instead of `"and"`.
Approach is to verify that onsets, durations and amplitudes match before taking the intersection.
> ENH: Fix factor transform to produce variables of same length, enable boolean transforms

- bids/analysis/tests/test_analysis.py
- bids/analysis/tests/test_transformations.py
- bids/grabbids/bids_layout.py
- bids/grabbids/config/bids.json
- bids/grabbids/config/derivatives.json
- bids/grabbids/tests/test_grabbids.py
- bids/grabbids/utils.py
- bids/variables/tests/test_collections.py
- bids/variables/tests/test_entities.py
- bids/variables/tests/test_io.py
- bids/variables/tests/test_variables.py
- bids/version.py
This PR patches pybids to be compatible with recent changes to grabbit. The main change is the addition of a new `name` field to the JSON config files, which is now mandatory in grabbit in order to support named domain functionality. Handling of derivatives is also modified to fit with grabbit's ability to handle hierarchical specifications. These changes should be fully backwards compatible for the vast majority of users. (The exception being specification of the `extensions` argument in the `BIDSLayout` init, as that argument is now removed. But I'd be very surprised if anyone's using that in the wild, as we only recently added it as a stopgap measure until the now-committed grabbit changes).
TODO: grabbit entity specifications now support a `dtype` field, so we should probably make a …
> Grabbit fixes

- .coveragerc
- .travis.yml
- bids/version.py
- setup.py
Data packaging was broken, but we didn't notice because pip was installing in editable mode on travis. This patches setup to install all data files, and also changes the travis config so pip installs normally. Fixes #138 and #143.
> Packaging fixes

- bids/grabbids/bids_layout.py
- bids/grabbids/tests/test_grabbids.py
Adds a `.description` field that contains the contents of `dataset_description.json`. Also nags and complains if the file is missing, or if it's present but lacks the mandatory fields `Name` or `BIDSVersion`.
p.s. STFU @choldgraf
> load and validate dataset_description.json; closes #151

- bids/analysis/analysis.py
- bids/analysis/auto_model.py
- bids/analysis/tests/test_transformations.py
- bids/variables/variables.py
Per discussion with @effigies, decided variables should filter after transformations even though user may not know which variables result from transformations. Otherwise `variables` and `HRF_variables` will be select at different times.
Also, added a check that `HRF_variables` is a subset of `variables`. I assume that `variables` is mandatory at the first level.
Closes #181.
> Filter variables after transformations

- .travis.yml
- codecov.yml
To avoid getting caught by API changes or have an opportunity to catch upstream bugs, we should test on pre-releases.
For speed, this replaces Miniconda with Travis's built-in Python environments, except for OSX, which still needs Miniconda.
Also, updated pytest to use parallelism and output coverage that Codecov can use.
>  CI: Pre-releases, Python versions, Codecov

- bids/variables/io.py
In `variables.io`, loop over `get_events` results, rather than merging, to avoid inserting unnecessary `n/a`s
> Loop over get_event files, instead of merging

- bids/grabbids/bids_layout.py
- bids/grabbids/tests/test_grabbids.py
- bids/version.py
This PR updates pybids to reflect changes to the grabbit API introduced in version 0.2.0 (see grabbles/grabbit#69). Although the grabbit changes are backward incompatible, pybids should maintain compatibility with existing code in the vast majority of cases (the exception being cases where the user is passing multiple paths and/or domain configurations). Also, since the name of the first argument has changed from `path` to `paths`, code using named args will need a trivial fix.
> grabbit-related updates

- bids/version.py
It is just an empty list since all of them moved into the main
set of dependencies, but this would allow external tools which
demanded it before still function without fixups, see e.g
https://github.com/nipy/heudiconv/issues/235#issuecomment-408193202
> BF: return back "analysis" installation scheme if someone relied on it

- bids/tests/__init__.py
Closes #220 by preventing tests from being imported when accessing `get_test_data_path`.
> don't need to import tests in __init__.py

- README.md
- bids/version.py
I've added a link in the README to binder so that people can run the tutorial without having to download anything.
The change that needs more careful review is that I've added `pytest` and `duecredit` to [`bids/version.py`](https://github.com/INCF/pybids/pull/225/files#diff-bf0ebf03d2ee99d8b4c3ca51e95c3495).
Pytest is necessary, duecredit just shows a warning when it can't be found.
Happy to iterate if needed!
> Add binder link for tutorial

- doc/introduction.rst
The link to pybids issues on NeuroStars yields [an incorrect page](https://neurostars.org/t/pybids). This fixes the link to point at [issues tagged `pybids`](https://neurostars.org/tags/pybids) !
> [DOC] Update neurostars link in sphinx site

- bids/layout/tests/test_layout.py
It should be legal to parse a directory with derivatives or sourcedata in the root path without making exceptions.
This tests that any exclusion is performed on values under the root, not the root path.
Related to discussion in poldracklab/fmriprep#1251, [Neurostars #2245](https://neurostars.org/t/fmriprep-no-bold-images-found-for-participant/2245/23).
> TEST: Restricted words are allowed in layout root

- .travis.yml
- bids/reports/tests/test_parsing.py
- bids/reports/tests/test_report.py
Working off of [Matching Jobs with `allow_failures`](https://docs.travis-ci.com/user/customizing-the-build/#matching-jobs-with-allow_failures).
Closes #276 
Closes #289
> TEST: Update pytest fixture usage; CI: Allow failures for Python 2.7 pre-release tests

- .gitignore
- bids/layout/layout.py
- bids/layout/tests/test_metadata_index.py
This addresses #291 
I actually just realized the core issue of this is related to #281 
The issue is that named tuples have `filename` instead of `path`. Since those are going to be deprecated, I'll update this PR accordingly and merge that branch.
This PR then fixes:
> Fix metadata search

- bids/layout/layout.py
- bids/tests/data/ds005/derivatives/events/dataset_description.json
- bids/tests/data/ds005_derivs/dummy/dataset_description.json
- bids/tests/data/synthetic/derivatives/fmriprep/dataset_description.json
`PipelineDescription.Name` should be a nested field, not a flat name. 
Related: https://github.com/poldracklab/fmriprep/issues/1384
> Fix: Set pipeline name to nested dictionary

- bids/reports/utils.py
- bids/version.py
This takes up a lot of space in the Travis output. Nibabel 2.1 is several years old now, so this minimum version should not cause any pain.
> FIX: Remove deprecated get_header call

- bids/variables/kollekshuns.py
- bids/variables/variables.py
Passing `sampling_rate` to `get_design_matrix` currently doesn't resample `DenseRunVariable`s.
> FIX: Resample dense variables properly in to_df

- bids/analysis/hrf.py
`np.ceil` is a conservative interpretation of a float for number of elements to create with `linspace`, ensuring an oversampling rate of at least that specified. If approximate is all that's needed, then `floor` might save a little computation, and `rint` would be the best approximation.
> FIX: numpy.linspace parameter num must be integer

- bids/layout/layout.py
Close #296 
Output is like:
```
<BIDSFile(subject=10, session=2, task=rest, acquisition=prefrontal, suffix=physio, datatype=func)>,
<BIDSFile(subject=10, session=2, task=rest, acquisition=fullbrain, run=2, suffix=physio, datatype=func)>,
<BIDSFile(subject=10, session=2, task=rest, acquisition=fullbrain, run=1, suffix=physio, datatype=func)>,
<BIDSFile(subject=10, session=2, task=rest, acquisition=prefrontal, suffix=bold, datatype=func)>,
<BIDSFile(subject=10, session=2, task=rest, acquisition=fullbrain, run=1, suffix=bold, datatype=func)>,
<BIDSFile(subject=10, session=2, task=rest, acquisition=fullbrain, run=2, suffix=bold, datatype=func)>,
<BIDSFile(subject=10, session=1, suffix=scans, scans=/home/zorro/repos/pybids/bids/tests/data/7t_trt/sub-10/ses-1/sub-10_ses-1_scans.tsv)>, …
```
> Add repr to BIDSFile

- bids/analysis/analysis.py
- bids/analysis/tests/test_analysis.py
Not quite #288, but achieves in the common case the goal aimed at by having an `Analysis.get_tr()`, which is to establish the sampling rate to be passed to `get_design_matrix`.
Also establishes the rough method for pulling out the TR from series of `AnalysisNode`s, which will be useful in implementing that functionality.
> ENH: Resample design matrix to 1/TR by default

- README.md
updating an old INCF reference in the link to bids-standard to fix the "build unknown" of the travis badge.
> repair travis badge

- bids/config.py
- bids/layout/__init__.py
- bids/layout/layout.py
Closes #312 
I did this in the simplest way possible that went with the `bids.config` mechanism we already have in place.
To specify a new config file you would so something like:
```
from bids import config
cf.set_option('config_paths', {'myextra': 'mypath', **cf.get_option('config_paths')})
print(cf.get_option('config_paths'))
> {'myextra': 'mypath',
>  'bids': '/home/zorro/repos/pybids/bids/layout/config/bids.json',
> 'derivatives': '/home/zorro/repos/pybids/bids/layout/config/derivatives.json'}
```
I think that's self explanatory enough for the rare situation people need to do this, and also cleans up `BIDSLayout's` code a bit. We could add a convenience function that appends to the config in a cleaner form if we wanted.
> Allow extra configuration files through module level config

- bids/analysis/analysis.py
- bids/analysis/auto_model.py
- bids/analysis/tests/test_analysis.py
Contrast type: 't' was incorrectly capitalized, which is not in accordance with the BIDS StatsModels spec.
This PR fixes that
> Lowercase t-contrast

- .travis.yml
- bids/version.py
This may be the root of the Pandas nightly failures.
> CI: Disable allowed failures for Python 2.7 nightly tests

- bids/analysis/analysis.py
```Python
analysis = Analysis(layout=layout, model=model_file)
selectors = analysis.model.get('input', {})
pprint(selectors)
analysis.setup(desc='preproc', subject=participants, drop_na=True)
selectors = analysis.model.get('input', {})
pprint(selectors)
```
Yields
```Python
{'task': 'facerecognition'}
{'task': 'facerecognition',
'desc': 'preproc',
'subject': ['01', '02', '03'],
'drop_na': True}
```
I assume the intended behavior is a temporary dictionary containing all of these keyword arguments, rather than updating the `input` dictionary in-place.
> FIX: Do not update model input selectors in-place

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
When a bad `target` argument is passed to `get`, suggests viable candidates instead of failing silently. Closes #266.
> Adds target hints

- bids/version.py
got following crash
```
File "/home/adina/Repos/pybids/bids/variables/io.py", line 229, in _load_time_variables
'regressors', sr)
File "/home/adina/Repos/pybids/bids/variables/variables.py", line 380, in __init__
self.index = self._build_entity_index(run_info, sampling_rate)
File "/home/adina/Repos/pybids/bids/variables/variables.py", line 418, in _build_entity_index
self.timestamps = pd.concat(_timestamps, axis=0, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'
```
and according to the https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.concat.html  sort parameter was introduced in pandas 0.23.0
@yarikoptic says Hi
> Demand pandas >= 0.23.0

- examples/pybids tutorial.ipynb
The link to the "derivatives config file" in the example notebook seems to be broken since v0.7.0.
It currently links to https://github.com/bids-standard/pybids/blob/master/bids/grabbids/config/derivatives.json, which doesn't exist anymore.
I updated the link to https://github.com/bids-standard/pybids/blob/master/bids/layout/config/derivatives.json, as I assume that it should link to this config file.
> Updates link to derivative config file in notebook

- .travis.yml
- bids/layout/layout.py
- bids/layout/tests/test_rootpath.py
- bids/tests/test_rootpath.py
- bids/version.py
Pathlib is great, and works out of the box in pybids on python 3.4+. I only had to tweak the argument validation slightly.
> Support pathlib.Path and other Str-castable types

- bids/variables/kollekshuns.py
Fix #349 
sampling_rate = 'auto' should be confined to `merge_collections` and not passed onward to `BIDSRunVariableCollection`
- Added fix for setting sampling_rate to that set by `merge_variables`
- Added check for non-string sampling_rate
@Shotgunosine does this fix your issue
Still need to add a test. Turns out there were no tests of merging Dense variables
> If sampling_rate is auto, set to first rate of DenseRunVariables

- bids/variables/__init__.py
- bids/variables/variables.py
Previously, a Split transformation failed, ref: https://github.com/bids-standard/pybids/issues/352.
This PR should hopefully fix this.
Also, @yarikoptic annihilated BIDSRunInfo which is not present anymore.
> ENH/BF: add check for run_info to be a list, pass run_info in correct position.

- bids/variables/io.py
Kind of fixes #355. Turns out the nifti (and BIDS metadata) had a TR of 2.00001 (or thereabouts), which caused a misestimation of duration, which caused one extra volume on a long time series.
This fix allows the change in the JSON sidecar (easier than editing NIFTI headers) to take effect. We should also generally prefer JSON metadata to NIFTI headers, anyway.
> FIX: Use BIDS metadata for TR over nii header

- bids/layout/layout.py
spotted while trying to run tests on datalad_neuroimaging.  So far that was the only problem although our tests do not look "too deep". Eventually will do more checks.
Cheers!
> BF(PY2): retain compatibility with Python 2 by using io.open

- bids/variables/tests/test_variables.py
- bids/variables/variables.py
Fixes the dimension mismatch after resampling described in #358 and  #361.
@yarikoptic and I suspect that the problem lies within the recomputation of num with `num = int(np.ceil(n * sampling_rate / old_sr))` -- if done per each run with up/downsampling adapted to the runs data it might explain why it results in failures for some runs of mine, but not for others. 
Its not an ideal solution, but for now we reassign num to the length of self.Index instead of recomputing and ignore it when there is a slight difference in length (of 1), and if there are larger deviations in length (>1) we blow up.
I put the commit on top of @effigies test in 8cfba06 (which passes with the change).
> FIX: Edge case where a resampled column was too-long-by-one

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/compute.py
- bids/variables/io.py
- bids/variables/kollekshuns.py
- bids/variables/tests/test_variables.py
- bids/variables/variables.py
`SimpleVariable.__init__` does not take a `run_info` parameter, while `SparseRunVariable.__init__` does. Further, the order of the other variables is inconsistent, so subclassing works poorly. The fix in #353 used positional arguments, which worked for `SparseRunVariable`, but failed for `SimpleVariable`. This fix uses kwargs to avoid the ordering problem. Because `SparseRunVariable.__init__` accepts a `**kwargs` parameter and does nothing with it, this is safe.
Related to #352/#353. I think there was another issue where I ran into this, but I can't find it right now.
Cherry-picked from #376.
> FIX: Pass new variable args as kwargs in split()

- bids/layout/layout.py
Updated use of get_fieldmaps to use the recommended file.entities['suffix'] internally
Now it shouldn't throw warnings to the user with every use.
> Removing internal use of deprecated file.suffix

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
- also made the test on "dirs" return type verify that return value is sorted
will be useful as preventative measure for demos/tutorials to not change their output randomly
> ENH: .get() - natural_sort BIDSFile entries as well for consistency

- .travis.yml
- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/compute.py
Fixes #354 and related to #356 
Profiling indicates that the slow function is actually `np.convolve` itself. It calls `np.correlate` which takes exponentially longer as the variable grows in length. 
(see: https://github.com/numpy/numpy/issues/1858)
The good news is that by not densifying prior to convolution things go *much* faster. 
For example, a predictor with ~850 events takes about 15ms as sparse, but 1.03s when upsampled to 10hz. 50hz takes that up to about a minute (I did the profiling on that).
The question that remains is how to downsample at the end. As it is, it will use the original onsets as the `frame_times`. That is, it will resample only at those onsets. Does that make sense? Or would uniform resampling at the TR (or some factor above that), be better? Maybe we can even …
> ENH: Improve convolution performance for Sparse variables

- bids/layout/core.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
But what I wondered if `absolute_path` is really something to be defined at the Layout level, or should be just a (yet another) option to `.get` -- seems to neither (nor tested) anywhere besides in `.get()` and indeed it is more of an option on how to report paths/directories .  If not for  #397 I would have immediately added to `get` with default of `None` describing it as the way to overload the value defined at the class level (probably should be retained for compatibility for awhile). Let me know if I should do that @tyarkoni
> ENH: respect absolute_path also for "dir" return_type

- bids/variables/variables.py
@yarikoptic and I were thinking about what is happening here. It seems to us as if `onset` is assumed to be non-decreasing within a run, and non-increasing across/at the change of runs, because whenever a subsequent onset time is smaller than the previous one, the event seems to be assigned to the next run (or rather: the run count `run_i` gets increased). If is is the case that runs are incremented based on onset, would that not be incorrect logic as it would imply that...
- I can't have an events.tsv file with unsorted onsets, for example when appending interleaved events and their duration event-wise 
as in 
Event      | Onset
----------- | --------
Event_A  | 1.0
Event_A  | 5.0
Event_B  | 2.0
Event_B  | 6.0
[...]
(or have we overlooked `onsets` being sorted earlier?, or thinking wrong …
> ENH: issue warning when silently incrementing runs

- bids/analysis/tests/test_transformations.py
- ENH: do not hardcode numbers
- use collection only for 2 subjects out of 16 (could even be just 1 may be)
- cache the collection, i.e. not regenerate in fixture each time (I initially pushed, then killed it, then revived it fixing that side-effect - just always return a clone!)
Also in principle, if tests take proper care about cloning where needed, then no caching would be needed, fixture could get `(scope="module")` and get called only once - giving even more speed up.  But ATM some test(s) do cause inplace modifications of the collection, and I didn't want to just blindly add `.clone()` everywhere, so added it once in the fixture.  The whole test_transformations.py runs 7 sec for me now (instead of 150 originally), but I think even this is too much given that it really doesn't …
> ENH(OPT,TST): make test_transformations run 7 sec instead of 150 or so

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/munge.py
in the code .values() is accessed later on, and if order is random, would not
correspond to the actual columns values, causes "random effects".
Closes #423
So if someone used Filter with both `query` and `by`, then better used python 3.7, or otherwise should redo their analysis ;-)
> BF: use ordereddict because otherwise columns might not be correctly assigned

- bids/layout/layout.py
Closes #384 
This is a suggestion for a note in the docstring and documentation for layout.py in order to inform about some API-changes from 0.6.0 to 0.7.0.
I have tried to follow the style from other notes, but could very well have messed something up.
> Update layout docstring to mention old behavior

- bids/layout/tests/test_writing.py
Not sure why the tests are failing on Python 2 all of a sudden, but rather than delve into it, I'm just turning on `ignore_errors=True` in `shutil.rmtree`, since the problem is a failure to delete a directory that doesn't exist, and everything else is passing.
> ignore rmtree errors

- bids/layout/config/bids.json
I wondered if there is some kind of way to automate testing of those... e.g. I think **all** files under sub* directories should have extension defined - we could check.
[There is also a question](https://github.com/bids-standard/bids-specification/pull/152#discussion_r282871911) of either extension should or should not contain a leading period but that is orthogonal to this, just linking related changes ;)
> BF: missing period before {extension} group for some dwi/ files

- setup.py
Per @effigies, GitHub used-by tracking apparently doesn't work if the setup.py name is imported from somewhere else. This should hopefully fix that.
> Set name explicitly in setup.py

- bids/layout/config/bids.json
This PR fixes a typo introduced by [this commit](https://github.com/bids-standard/pybids/commit/2e532e2b76ebbab1582685f237556a761d11b669) in the `bids.json` config file.
In addition, it adds `eeg` in `datatype` to support EEG datasets. 
Note that for some reason, *channels.tsv, *electrodes.tsv, *events.tsv are not read for some reason which may be due to a different issue?
This fixes partly #454.
> ENH: Add eeg datatype to layout config; FIX: Typo

- bids/layout/models.py
- bids/layout/tests/test_models.py
This allows us to use `Path(layout.get(...)[0])`, or to pass `BIDSFile`s to functions that expect path-likes, such as `os.stat` in 3.6+, or `pandas.read_csv`.
Nothing revolutionary, but somewhat convenient when you forget that `get()` returns `BIDSFile`s.
> ENH: Add BIDSFile.__fspath__ to work with pathlib

- bids/layout/layout.py
If a `pathlib.Path` object is passed to `BIDSLayout` as root, then `os.path.join(root, ...)` will fail on Python <=3.5.
This change defers instantiation of `BIDSLayout.ignore` and `BIDSLayout.force_index` until after `_validate_root` coerces `BIDSLayout.root` to a `str`.
> FIX: Instantiate ignore/force_index after root validation

- bids/analysis/hrf.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_models.py
That stripping might be undesired (was it left for compatibility? then having at least a comment in the code would be useful) so if needed 7d3a7294d428d2d2f43c1d2c5f9f3094e6daffe5 could be dropped
> ENH(DOC)+RF: unify docstring to be imperative, strip away unused kwargs to BIDSFile

- bids/layout/config/bids.json
To keep consistency with the spec, I'm proposing the following changes:
To keep consistency with other entities of the config:
> FIX: Minor fixes regarding BOLD files naming

- bids/layout/models.py
- bids/layout/tests/test_models.py
This doesn't actually fix #465, but it closes #466, which is independently useful. (We should probably improve the `__repr__` of other models as well at some point, but the vast majority of collisions of the kind in #465 are going to affect the `Tag` model).
> adds more sensible repr to Tag; closes #466

- .gitignore
- .travis.yml
- bids/version.py
Adds `test`, `travis_tests` and `tutorial` extras to unify the installation process on Travis and reduce some of the `if`/`else` mess.
Spin-off of #470. Not really necessary, especially as what I was trying to enable isn't feasible, but I think it makes things a little cleaner, so here it is.
Threw in a `.gitignore` update.
> MAINT/CI: Use `extras_require` to declare dependencies for tests 

- bids/layout/config/bids.json
CBV and phase are accepted functional MRI modalities, per the specification, so I'm adding them to the BIDS layout func path pattern. They are also being added to the specification's Entity table in bids-standard/bids-specification#312.
> FIX: Add CBV and phase modalities to func datatype path pattern

- .zenodo.json
- tools/prep_zenodo.py
The goal of this PR is to update our titles to enable the JOSS process (https://github.com/openjournals/joss-reviews/issues/1294) to finish with the next release.
* Adds a title consistent with the JOSS title
* Adds a description from README.md - this will remove the release notes from the Zenodo entry, I believe, but I'm not sure how valuable that is to Zenodo landing pages.
* Update the tags to be a bit more findable.
* Updates `tools/prep_zenodo.py` to avoid reordering title and description out of prominence.
Perhaps we want to make an RC release just to see if it works without causing everybody to upgrade a bunch while we iterate?
> MAINT: Additional Zenodo metadata

- .zenodo.json
- bids/layout/layout.py
Previously build_path will fail if one of the loaded configs fails to specify default_path_patterns.
> Check that default_path_patterns is not None before using in "build_path"

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Fixes #490 by automatically trying to convert every entity value passed as an argument to `BIDSLayout.get()` to the appropriate data type (as encoded in the `.dtype` field of the corresponding `Entity`). This fails silently to still allow the DB to reconcile different types.
> FIX: Automatically sanitizes dtype of get() arguments

- bids/analysis/tests/test_analysis.py
- bids/tests/data/ds005/task-mixedgamblestask_bold.json
- bids/utils.py
- bids/variables/entities.py
- bids/variables/io.py
- bids/variables/tests/test_collections.py
Fixes #451.
Basically just (a) drops (unnecessary) sorting on unimportant columns and (b) only uses a subset of entities to filter on existing nodes. A bit of extra work was required to refactor the `NodeIndex` class (adding an explicit `create_node()` method) in order to avoid having to deal with two different `entity` dicts (one for filtering existing nodes, one to assign to newly-created ones).
> Fix filtering and sorting on metadata in get_nodes()

- bids/layout/models.py
- bids/layout/tests/test_models.py
- bids/tests/data/synthetic/participants.tsv
- bids/variables/io.py
Ensures correct dtype enforcement for columns in files like `participants.tsv` that are defined in the spec has having a particular dtype (e.g., `subject` labels are strings).
Closes #480.
> Enforce dtypes on spec-defined columns when reading in DFs

- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
For unclear reasons (i.e., human error), the `_default_ignore` list was being... ignored by default (🥁). This patch ensures that passing `ignore=None` will ignore directories like `sourcedata/` and `code/`, and also that specifying `ignore` explicitly overwrites the defaults.
> Fix default ignore

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Forces the dtype of all entities to `str` when using `regex_search=True`.
Closes #509.
> FIX: use string dtype for all entities when using regex search

- bids/layout/layout.py
- bids/layout/tests/test_path_building.py
This will fail on the next line anyways if built is None, but at least this is more descriptive
> ENH: Raise ValueError if BIDSLayout.build_path fails to match any pattern

- doc/conf.py
Stubs weren't being generated by Sphinx (see thread in #499). This fixes that.
> FIX: auto-generate stubs

- .gitignore
- bids/layout/layout.py
- bids/layout/tests/conftest.py
- bids/layout/tests/test_layout.py
After a derivative directory has been created, storing a persistent sqllite database file on disk can dramatically improve subsequent queries.
In my current test case with 25808 files in the derivative directory, basic startup commands for creating the layout move from '98.77 seconds' to '0.03 seconds' needed to initialize the layout for querying.
```python
import time
import sys
from bids import BIDSLayout
bids_dir = "/Users/johnsonhj/data/MediumTestingData/"
start_time = time.time()
layout = BIDSLayout(
bids_dir,
database_file="bidsdb.sql",
derivatives=["/Users/johnsonhj/data/MediumTestingData/derivative_outputs_nonstandard_derivative_directory"],
)
end_time = time.time()
elapsed = end_time - start_time
print("{0:.2f} seconds".format(elapsed))
all = layout.get(scope="derivatives", …
```
> Improve derivative database mode

- .gitignore
- bids/layout/layout.py
- bids/layout/tests/conftest.py
Files with .sql extention are expected to have SQL code in them. The
binary data files written by sqlite should have an appropriate .sqlite
extention.
> STYLE: .sql is a misleading extension to sqlite files

- bids/variables/tests/test_variables.py
- bids/variables/variables.py
hopefully this will address #373 
however, before this is merged, i need to understand some bids fu. why is shape (nvols, 1) in the test? is only 1 timeseries being extracted from the image array?
my plan was to insert a sin wave between the nyqist freq of the original rate and the nyqist freq of the new rate. if you don't lowpass the signal prior to interpolation, then the original freq will get aliased in. so the test would check if the amplitude of the expected alias is close to 0 or not.
> fix: filter before downsampling

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/__init__.py
- bids/analysis/transformations/base.py
- bids/analysis/transformations/compute.py
- bids/analysis/transformations/munge.py
- bids/variables/kollekshuns.py
- bids/variables/tests/test_collections.py
- bids/variables/variables.py
This PR implements a number of improvements, mostly focused on transformation handling:
* Implement supports for variable groups (essentially just aliases to multiple variables), as documented in the BIDS-StatsModel spec.
* Adds the `Group` transformation, per the spec, which enables explicit creation of variable groups.
* Improves/cleans up the `Split` transformation and updates the returned variable names to reflect the spec
* Generalizes the `Collection.match_variables()` method to allow unix-style pattern matching.
* Implements transformation argument wild-card expansion (closes #487).
> ENH: Transformation-related improvements

- bids/layout/layout.py
- bids/layout/tests/conftest.py
- bids/layout/tests/test_layout.py
Closes #538 
Saves db files and initialization arguments (as JSON) into a folder. Each derivative gets its own folder within the main folder. 
This also checks to see that initialization arguments match the ones in the JSON file, when loading from disk. If they don't match, it throws an error. 
It could be argued that instead it should just warn you that arguments will be ignore, but I prefer to throw an error so that users think about what arguments they're passing, and how that may affect indexing. If they need to reindex, they can
> Save BIDSLayout + Derivatives to folder (with init arguments)

- bids/layout/layout.py
- bids/layout/tests/conftest.py
- bids/layout/tests/test_layout.py
- A nicer error message if your db's init arguments mismatch the ones you ask for
- More importantly, a classmethod `load_from_db` that will load the `BIDSLayout` using the init arguments found in the `JSON`
- Finally, saves the actual untouched arguments passed into `BIDSLayout` to JSON.
> Helpful error for db argument mismatch, and add classmethod load_from_db

- README.md
According to the [release notes for PyBIDS 0.10.0](https://github.com/bids-standard/pybids/releases/tag/0.10.0), it has now dropped Python 2 support. How about updating the README to reflect that?
> DOC: Remove Python 2 support statement, now that v0.10.0 has dropped it

- bids/layout/layout.py
Looks like a copy-paste error dropped a line in the helpstring for `BIDSLayout`'s `write_contents_to_file` method when it was copied from the above `build_path` method's helpstring. This PR fixes it.
Fixes  #563.
> Fix "strict" helptext in BIDSLayout.write_contents_to_file

- bids/layout/layout.py
- bids/layout/writing.py
Just a helpstring fix.
These symbols - < > - are angle brackets, not "carets". Typographically, a [caret](https://en.wikipedia.org/wiki/Caret) is an upward pointing chevron or arrow thingy, like ^ or ‸.
> Correct term "caret" to "angle bracket" in helpstrings

- bids/analysis/auto_model.py
- bids/analysis/hrf.py
- bids/config.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/writing.py
- bids/reports/utils.py
- bids/variables/entities.py
- bids/variables/io.py
- bids/variables/kollekshuns.py
- bids/variables/variables.py
Looks like there's a couple typos in the code's helpstrings and comments. Here's some suggested fixes.
> Fix typos in helpstrings and comments

- bids/variables/tests/test_variables.py
- bids/variables/variables.py
Proof-of-concept to accompany #568.
Related:
* https://github.com/bids-standard/pybids/pull/568#discussion_r364421607
* https://github.com/bids-standard/pybids/issues/361#issuecomment-571254503
> ENH: Calculate default sampling rate for SparseRunVariable.to_dense

- bids/variables/kollekshuns.py
Fixes #361 
The issue is that when you call `to_df` on `BIDSRunVariableCollection`, the `resample` method will call `to_dense` on any `SparseRunVariable`. 
The problem with that is that calling `to_dense` only takes samples at the output `sampling_rate`. If that sampling rate is low (such as "TR" in `get_design_matrix`), it will simply ignore any values that don't coincide with the TR. 
Instead, now it will upscale with `to_dense` to the sampling_rate of the collection (10hz by default), and then resample to the TR.
> Upscale to collection sampling rate prior to resampling

- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
closes #558 
adds the ability to do partial metadata indexing (to help speed up creating a layout).
> ENH: enable partial metadata indexing

- bids/layout/layout.py
Fixes #557 and #555 
- Uses only the presence of 'derivatives' in config to determine if a `BIDSLayout` is in the `derivative` domain. I could see an argument that we should consider all which have more than only the core `bids` config listed.
- I used some very inelegant (rather janky) counts using just the `Tag` model as Tal suggested. 
%timeit results using the `synthetic` test dataset:
Previous method: 606ms
This PR: 4.99ms
Only counting distinct session id's, not nested within subjects: 3.99ms (so not worth only doing this)
I will say that just doing `layout.get_subjects` takes 35ms on this dataset, so there's room for optimization on `.get`. 
On a real dataset with no sessions (life), I saw a 10x speedup: 2.83s vs 0.27s
> FIX: Domain entity, and slow __repr__

- bids/layout/tests/test_writing.py
- bids/layout/writing.py
(replaces #575)
Entities containing lists are expanded to generate all the possible combinations for all given entities (e.g., all subjects, tasks and runs that match a pattern). Just like:
```Python
>>> # Lists of entities are expanded
>>> entities = {
...     'extension': 'bvec',
...     'subject': ['%02d' % i for i in range(1, 4)],
... }
>>> build_path(entities, patterns, strict=True)
[
'sub-01/dwi/sub-01_dwi.bvec',
'sub-02/dwi/sub-02_dwi.bvec',
'sub-03/dwi/sub-03_dwi.bvec'
]
```
Follows up on #574.
> ENH: Extend ``build_path`` to generate lists of files

- bids/layout/index.py
bids_validator uses regexp that hardcodes `/`, but on Windows `os.path.sep` returns `\\`, so the comparison always fails.
There may be other locations where `os.path.sep` is used which is also problematic, but this was this first one I encountered and at least allowed me to validate my top-level files.
> Replace os.path.sep with fwdslash because bids validator hardcodes fwd

- bids/utils.py
- Closes #588 
Values to be replaced were being modified to lower case by `convert_JSON`. Fixes this by adding an exception if parent key == `Replace`.
I looked at the spec, and looks like this is the only transformation argument that is a dict, so there shouldn't be other cases of this issue.
> Add Replace as exception to recursive JSON conversion

- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/layout/tests/test_utils.py
- bids/layout/utils.py
- setup.cfg
As discussed in poldracklab/fitlins#223, a common idiom is to retrieve metadata as a dictionary and then query it, resulting in opaque `KeyError`s when the sought term is absent. This PR makes a simple subclass of `dict` that retains the name of the file the metadata dictionary was produced by for inclusion in the error message.
The advantage of this approach is that downstream tools will get the reporting improvement for free without needing to change their method of fetching metadata.
> ENH: Add BIDSMetadata dictionary to report file with missing metadata

- .travis.yml
Closes #535.
Do we want to follow [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) or something similar? If so, we should be dropping Python 3.5.
For reference, nibabel and nipype are following NEP29 + 1 year.
> CI: Test on Python 3.8

- bids/layout/models.py
This allows for things like `bids_file.get_image(mmap=False)`.
NBD if this seems out-of-scope. With recent nibabel, `nb.load(bids_file, mmap=False)` works just fine, since we support the `__fspath__` protocol.
> ENH: Pass kwargs from BIDSImageFile.get_image() to nibabel.load

- bids/analysis/tests/test_analysis.py
Got around to debugging the test failure. Looks like it was probably in the new model spec stuff (#548), and was only passing by chance. `get_collections()` return ordering seems to depend on dictionary or set ordering somewhere, so it's deterministic in Python 3.6+.
This makes an equivalent test where we don't care which subject's entities get returned. Marked with PY35 so we can revert in the future.
> FIX: Make entity assertions Python 3.5-safe

- bids/layout/models.py
- bids/layout/tests/test_models.py
Fixes a bug reading from `.tsv.gz` files in `BIDSDataFile.get_df()`, where the first line was interpreted as a header. Also passes through keyword arguments to `pd.read_csv()`, since we're already doing something similar for NiBabel (see #601).
Closes #570.
> FIX: Bug in BIDSDataFile.get_df()

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Closes #603. Also removes deprecation warning about `extensions` disappearing in 0.11, as we're about to release 0.11.
> FIX: Bug in get() when passing enums as extensions

- bids/layout/layout.py
See #533 for problem description. The solution was weirdly trivial: I removed eager loading of `BIDSFile` and `Tag` associations in the query-building. It makes sense that this would dramatically speed things up for queries over large datasets (as these tables can get pretty big); the surprise is that this doesn't break anything, as I only introduced the eager joining in order to solve some earlier problems with SQLite connections detaching when mixing databases. My best guess would have been that SQLAlchemy fixed something in a recent version, but it turns out I was still running 1.3.8 (over a year old) until just now. So I'm frankly at a loss. But as long as this doesn't cause any test failures on Travis, and nobody else complains, I think this is the sensible course of action, as it …
> FIX: Certain queries involving multiple layouts are very slow

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/compute.py
> FIX: Scale transformation fails if passed constant input.

- bids/reports/parsing.py
- bids/reports/report.py
- bids/reports/tests/test_report.py
Closes #599.
Changes proposed:
- Add new BIDSReport method: `generate_from_files()`. This method takes in a list of BIDSImageFile objects and builds a report just from those files. This is an alternative to using `layout.get()` to select files, since some tools build their file lists from multiple searches.
- Fix a minor bug in reports/parsing.py where missing run entity led to "Zero runs" in report.
- Add test for `BIDSReport.generate_from_files()`.
> ENH: Add method to generate report from list of files

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Replaces the `drop_invalid_filters` argument to `BIDSLayout.get()` with an `invalid_filters` argument that behaves as described [here](https://github.com/bids-standard/pybids/issues/596#issuecomment-614238482). Valid options are `'drop'`, `'allow'`, and `'error'`.
This introduces breaking changes, both in terms of the argument name, and the new default behavior (to raise an error, instead of silently dropping invalid filters).
Closes #596.
> ENH: Improved handling of invalid filters

- .travis.yml
Travis is failing because numpy 1.19rc1 is being installed but there are no wheels for Python 3.5.
> CI: Drop --pre check for Python 3.5

- bids/layout/layout.py
fixes #619 
This pull request adds two strings that give examples of a dataset_description.json for a BIDS and Derivatives dataset (pulled directly from [the bids specification](https://bids-specification.readthedocs.io/en/stable/))
Here is an example error message:
```
Traceback (most recent call last):
File "<stdin>", line 4, in <module>
ValueError: Mandatory 'Name' field missing from dataset_description.json. Here is an example dataset_description: 
{
"Name": "The mother of all experiments",
"BIDSVersion": "1.0.1",
"License": "CC0",
"Authors": [
"Paul Broca",
"Carl Wernicke"
],
"Acknowledgements": "Special thanks to Korbinian Brodmann for help in formatting this dataset in BIDS.",
"HowToAcknowledge": "Please cite this paper: https://www.ncbi.nlm.nih.gov/pubmed/001012092119281", …
```
> [ENH] add example bids and derivatives dataset_description.json strings to error messages

- bids/exceptions.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
This is an initial shot, which Closes #473 if merged since original concern would be addressed.
But
- I wonder if I have not overdone it a bit ;-)
- I think that many (if not all) of the `*BIDS*` exceptions should have ideally came from `bids_validator` package, and were not defined in PyBIDS
- I might have (or not) misinterpreted/attributed difference between "entity" (BIDS term) and target (more of a PyBIDS term).
But looking at the tests I think it becomes a bit clearer on what to expect to be raised, in comparison to IMHO abused `ValueError` (could come from anywhere).  I might have even made `BIDSValidationError` not a subclass of `ValueError` since we are not really talking about a value passed into a function in pybids (which is what typically ValueError is used for, and what I …
> ENH: Introduce PyBIDS exceptions

- bids/layout/index.py
Changed `'/'` to `os.path.sep`  which will work both with POSIX and Windows paths.
The issue where the problem was raised: bids-standard/pybids#425
> made _validate_file work on Windows

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Closes: #622 
Helps direct users to not pass in `filters` as a dictionary directly, but should have them do:
`layout.get(**filters)`
vs
`layout.get(filters=filters)`, which results in returning the entire bids root.
> Add explicit warning message when users pass in filters as a dictionary keyword

- bids/analysis/transformations/__init__.py
- bids/analysis/transformations/compute.py
#548 created a TransformerManager that normalized transformation names to lowercase, which would make `And` and `Or` conflict with the keywords `and` and `or`, so it postfixed these with underscores.
This PR applies the change to the `Transformation` subclasses, as well.
@tyarkoni Any reason to keep `And` and `Or` around as aliases?
> FIX: Post-fix And and Or transformations with underscore

- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_writing.py
- bids/layout/writing.py
For historical reasons, `BIDSFile.copy()` only supported copying text files, and did so by reading contents in and then writing them. This patch generalizes the previous workhorse `write_contents_to_file()` function to add support for direct copying. As a result, I've renamed it to `write_to_file()`.
Closes #514
> ENH: Adds OS-level file copying instead of reading/writing via Python

- bids/layout/layout.py
Reverts bids-standard/pybids#616
Fixes #625, reintroduces #533.
> Revert "FIX: Certain queries involving multiple layouts are very slow"

- bids/layout/layout.py
Closes #635 
Adds a check for the default config before querying it.
This is causing a failure within the templateflow client (and subsequently fmriprep + friends), so we should cut a new release once this is in.
> FIX: Preserve `get` logic when using custom config

- bids/utils.py
This helps ensure that double-extensions like `.dtseries.nii` or `.func.gii` get identified as neuroimages.
Backwards compatible, as file objects might become subclasses of their original objects, but won't go the other way.
> ENH: Catch any NIfTI/GIFTI (incl. CIFTI-2) files as BIDSImageFiles

- bids/variables/io.py
While working toward CIFTI-2 support in FitLins (poldracklab/fitlins#239), I don't think I can work around the need to fetch timing information from the files to be modeled. The alternative is to depend on the raw dataset, which needs to have the information but would be inefficient to fetch.
This change should be backwards compatible.
> ENH: Fetch number of time points from NIfTI, GIFTI or CIFTI-2

- bids/layout/__init__.py
- bids/layout/db.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/tests/conftest.py
- bids/layout/tests/test_db.py
- bids/layout/tests/test_layout.py
- bids/layout/tests/test_models.py
- bids/layout/tests/test_path_building.py
- bids/layout/tests/test_rootpath.py
- bids/layout/tests/test_utils.py
- bids/layout/tests/test_validation.py
- bids/layout/tests/test_writing.py
- bids/layout/utils.py
Reorganizes a lot of the functionality in `BIDLayout`:
* Most database-related functionality is now in a `ConnectionManager` class in a new `db` module.
* Also pushed setup of the `Config` objects into the `ConnectionManager` class.
* Moved some utilities out of `layout.py` and into `utils.py`.
* Made some static class methods functions to keep the `BIDSLayout` class more manageable.
* Streamlined the logic in the `BIDSLayout` init; should now be much easier to follow.
Cleaning up the session management seems to have magically resolved the problems in #533/#616/#625/#630, which was what originally motivated this PR—so that's a happy ending.
Closes #533.
> FIX: Remove need to eager load associations

- bids/layout/layout.py
Just drops a deprecation warning we slated for removal in 0.12.
> MNT: Remove deprecated database_file argument to BIDSLayout

- examples/pybids_tutorial.ipynb
This illustrates using this util independent of a specific layout. This change also includes the change in execution count of the subsequent code cells.
As suggested in #633 [(comment)](https://github.com/bids-standard/pybids/issues/633#issuecomment-654319454)
> Add example for using parse_file_entities from bids.layout

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/compute.py
Fixing #643.
Starting with a test.
To bring some context over, convolving a single, zero-duration event produces expected results. If a second event is present, zero duration or otherwise, then the logic currently uses the minimum duration to estimate a reasonable oversampling rate. When duration is 0, the rate is infinite, and problems are had.
> FIX: Convolve zero-duration (impulse) events when variable contains multiple events

- bids/__init__.py
- bids/layout/__init__.py
- bids/layout/db.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_db.py
- bids/layout/tests/test_layout.py
- bids/layout/tests/test_models.py
- bids/layout/validation.py
- bids/variables/tests/test_collections.py
The nominal point of this PR is to add a `.relpath` attribute to `BIDSFile` objects that returns the path relative to the `BIDSLayout` root. This provides a proper solution to #625, as it will allow us (in 0.14) to drop the `absolute_paths` argument to `BIDSLayout` that turned out to be the root of all evil.
Unfortunately (or maybe fortunately), adding the `.relpath` property required a non-trivial refactoring of quite a few modules. The reasons for this are probably not worth getting into, but the upshot is that many things are better organized now. Changes include:
* Most validation functionality formerly in `layout.py` is now in a new `validation.py` module. This is mostly cosmetic, but helps reduce the size of `layout.py` and centralizes all validation-related functionality in one …
> ENH: Add relpath attribute to BIDSFile and associated refactoring

- bids/layout/tests/test_layout.py
Drops a test that probabilistically fails and is no longer necessary following #647.
> FIX: drop obsolete test

- bids/cli.py
- bids/tests/test_cli.py
- bids/utils.py
- setup.cfg
To streamline operations that would require a dedicated script or starting an interactive python session.
Currently just supports generation of a database index, to facilitate processing of large datasets, as well as a version check. The database index can be customized by certain kwargs for `BIDSLayout` and `BIDSLayoutIndex` classes.
This should be extendible for other operations down the line.
- Adds `click` as a dependency - its handling of sub-parsers is a bit more intuitive than `argparse` IMO.
> ENH: Add CLI to PyBIDS

- Makefile
Should fix Travis.
ref: https://github.com/jupyter/nbconvert/pull/1192
> FIX: Explicitly convert to HTML when testing tutorial (nbconvert 6.0 breakage)

- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/layout/validation.py
Starting with a regression test.
Fixes #655.
> FIX: Sanitize single derivative Path passed to BIDSLayout

- bids/analysis/analysis.py
- bids/analysis/tests/test_analysis.py
This refactors the `Analysis` setup process so that it's possible to incrementally load data. See #670 for the use case. @adelavega, see the new test for usage: basically instead of calling `setup()` once, you call it repeatedly with `finalize=False` when doing the incremental data loading, and then you call `finalize()` once at the end.
No changes to the main `Analysis.setup()` call except for the addition of the new `finalize` argument, but there are some minor changes inside the `Step` class, so @effigies, note that if fitlins is currently manually setting up steps instead of doing it implicitly via `Analysis.setup()`, you'll probably need to tweak a couple of things (basically just call `add_collections()` explicitly, and then `setup()` after that).
Closes #670.
> [REF] Incremental variable loading in Step setup

- bids/analysis/tests/test_transformations.py
- bids/analysis/transformations/base.py
- bids/analysis/transformations/compute.py
- bids/analysis/transformations/munge.py
- bids/variables/variables.py
- Adds `_align` to logical operations.
- Remove `force` option from align method, and set default to equivalent of `False`.
- Add '_force_dense_align` class level attribute which controls if an error should be thrown in events are misaligned, or automatically densified to ensure alignment. 
Closes #648
> Require aligned input for logical operations

- bids/analysis/analysis.py
- setup.cfg
Trying to run fitlins tests and I ran into a pybids issue:
```
File "/data/nielsond/python/envs/fitlins_dev/lib/python3.6/site-packages/bids/analysis/analysis.py", line 103, in setup
selectors.pop('scan_length')  # see TODO below
KeyError: 'scan_length'
```
Based on feedback from @effigies, I added a default `None` to the  `scan_length` pops.
> FIX: Do not error when popping missing scan_length

- bids/layout/config/bids-nodot.json
- bids/layout/config/bids.json
BIDS has added new entities for flip angle (`flip`), inversion time (`inv`), magnetization transfer state (`mt`), and component of the complex signal (`part`). These entities have been merged into the specification, but the updates haven't been released yet, although we expect a release within the next month or so.
I didn't see any associated tests for the `echo` entity, so I'm guessing that there are no tests associated with the config files. Please correct me if I'm wrong.
Changes proposed:
- Add patterns for `flip`, `inv`, `mt`, and `part` entities.
- Incorporate `part` into path patterns. The other entities have not been integrated into any suffixes yet, as there are still BEP001-related PRs pending.
> ENH: Add flip, inv, mt, and part entities

- bids/layout/layout.py
- bids/tests/data/7t_trt/sub-01/ses-1/sub-01_ses-1_scans.json
When `BIDSLayout.__repr__` is called on datasets that have `sub-N_scans.tsv` files, the query to obtain runs also returns these files, and their value is a dictionary which is not hashable by the `set` object wrapping up the query.
Instead of refining the query (which indeed would fix the issue), this workaround uses the naive approach of ensuring that each result of the query has `int` value.
Resolves: #681.
> FIX: BIDSLayout -- TypeError: unhashable type: 'dict'

- bids/layout/tests/test_layout.py
- bids/tests/data/7t_trt/sub-01/ses-1/sub-01_ses-1_scans.json
Should take away the problem identified in https://github.com/bids-standard/pybids/pull/693#issuecomment-758706775, but without removing the test.
> FIX: Resolve side-effects of new testfile in #682

- bids/layout/index.py
- bids/layout/models.py
- bids/layout/tests/test_layout.py
Fixes #692. When more than one JSON file was present in the inheritance chain, the wrong file was being used as the direct sidecar for the target file (most distant instead of most recent). This didn't have any effect on the order in which metadata files were actually examined/indexed (i.e., the BIDS spec was still being followed correctly), which is probably why it took this long to notice it. It would only manifest in having the wrong associated files returned when calling `get_associations()` under certain conditions.
(In the process of fixing the above, I also caught another, undetected bug, where `include_parents` was being ignored when `kind` was set to `None`.)
> FIX: Correctly pair metadata file when creating association records

- bids/layout/config/bids.json
Following https://github.com/bids-standard/bids-specification/tree/master/src/schema/datatypes
Fixes #707.
> ENH: Update datatypes

- bids/layout/config/derivatives.json
Squashed #698 and updated.
* Space entity is already in bids.json, and duplicates aren't permitted.
* Might as well add the res entity while updating den
> ENH: Add res/den entities to derivatives.json

- bids/variables/variables.py
I believe this should fixes issue https://github.com/bids-standard/pybids/issues/702
cc: @effigies @tyarkoni
> FIX: Ensure indicator matrix is boolean when indexing in Split transformation

- bids/layout/index.py
This PR causes JSON files to be lazily loaded when needed to determine metadata, and changes the rules for what is "needed". 
* If a data file exists:
* Missing metadata produces an error
* If a data file does not exist:
* Missing metadata is silently skipped
* Existing metadata is loaded
An alternative is to always skip metadata for missing data files, but this would impede the useful facility of querying a dataset without fetching all of the data files at once.
Closes #631.
> FIX: Lazily load metadata, skip when missing data files are missing sidecars

- bids/analysis/tests/test_transformations.py
- bids/variables/collections.py
- bids/variables/entities.py
- bids/variables/io.py
- bids/variables/tests/test_collections.py
- bids/variables/tests/test_entities.py
- bids/variables/tests/test_variables.py
- bids/variables/variables.py
WIP Fix to #712 
- Keep track of `n_vols` in `RunInfo` (might be a good idea anyways)
- Use `n_vols` to compute the number of resample volumes in `resample` if `sampling_rate` == `TR`
- To do so, need to propagate the `TR` value one level up (instead of computing true sampling_rate at `Collection` level).
> Resample to n_vols for sampling_rate == 'TR'

- bids/_version.py
- bids/analysis/hrf.py
- bids/external/inflect.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_writing.py
- bids/variables/io.py
but that beast went into fixing some code variables which I decided
would be too much for this one, so just typos in doc/comments for now
> typos: as identified by codespell

- bids/layout/db.py
- bids/layout/layout.py
- bids/layout/models.py
Currently, selecting by tags is done using subqueries. For example, using the `get_fieldmap` function leads to the following database query containing three subqueries:
```sql
SELECT files.path, files.filename, files.dirname, files.is_dir, files.class_
FROM files JOIN tags ON files.path = tags.file_path
WHERE files.is_dir = 0 AND (EXISTS (SELECT 1
FROM tags
WHERE files.path = tags.file_path AND tags.entity_name = 'subject' AND (tags._value REGEXP '01'))) AND (EXISTS (SELECT 1
FROM tags
WHERE files.path = tags.file_path AND tags.entity_name = 'suffix' AND (tags._value REGEXP '(phase1|phasediff|epi|fieldmap)'))) AND (EXISTS (SELECT 1
FROM tags
WHERE files.path = tags.file_path AND tags.entity_name = 'extension' AND ((tags._value REGEXP 'nii.gz') OR (tags._value REGEXP 'nii'))))
```
If we …
> ENH: Improve `get` performance

- .github/workflows/package.yml
- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
- .zenodo.json
- CHANGELOG.rst
Quick bug-fix release before merging a major refactor that may start breaking downstream tools.
These aren't actually bugs, but they are useful to downstream tools.
@HippocampusGirl I have added you as an author for the Zenodo archive. If you would like a different name/spelling, to add affiliation and ORCID, or to decline to be listed as an author, please let me know (or make a code suggestion) ASAP.
> REL: 0.13.1

- bids/layout/tests/test_db.py
- bids/layout/tests/test_models.py
- setup.cfg
Left this off so long, we're almost ready to to drop 3.6...
Anyway, we haven't tested on 3.5 for a bit, and it's EOL, so let's just turn the crank.
Closes #666.
> MNT: Set minimum version to Python 3.6

- bids/layout/layout.py
Fixes #747 
This is a cheap fix for a bug that occurs when a `.tsv` meta-data entry (i.e. column description) matches a common BIDS entity.
For example, if you call `layout.get_tasks()`, it will first get all unique values for the `task` entity. However, if `index_metadata=True`, that includes all instances of `task` in `.json` sidecars for TSVs as well. However, `.json` sidecars for `.tsv` files are a different type of meta-data that describes the columns in TSV files, not the entities of the corresponding file. 
Thus, `get_tasks` will fail because it tries to take a set on a list that includes a `dict` value. Here, I simply excluded dict values from that operation.
> FIX: get unique, with conflicting meta-data

- bids/modeling/statsmodels.py
- bids/variables/collections.py
Currently the `force_dense=True` forces `to_dense` on all variables of the collection even when they are all instances of `DenseRunVariable`. This fix ensures that `to_dense` is run only on sparse variables.
cc: @effigies
> FIX: ensure force_dense=True runs to_dense only on sparse variables

- bids/layout/config/bids-nodot.json
Closes None, but fixes an oversight in #688. Specifically, in #688 I added the new entities to the entity list in both `bids.json` and `bids-nodot.json`, but only updated the `default_path_patterns` in `bids.json`. This PR updates the path patterns in `bids-nodot.json` to match `bids.json`.
> FIX: Add flip, inv, mt, and part entities to bids-nodot config

- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
If return_type = 'id' ("shorthand queries") or 'dir' and "target" is a core BIDS entity (i.e. one that is derived from filenames, not from meta-data), then only look at results that are not from meta-data.
If you ask for `layout.get_runs()`, it will only look at values that came from files, not meta-data.
This should prevent collisions from similarly named meta-data values. 
However, if you ask for a meta-data target, then it will attempt to take a `set` across all values it finds:
```
In [5]: layout.get(target='SliceThickness', return_type='id')
Out[5]: [1, 2.5]
```
Related #694
> FIX: Associate "is_metadata" with Tag, not Entity; and only return non-metadata entries for core Entities in get(return_type='id')

- bids/layout/layout.py
- bids/variables/io.py
- Fixes issue #748 for 0.13.x series
- Explicitly only searches for `.tsv` files when loading event regressors
> Patch 0.13.x maint branch 

- bids/analysis/analysis.py
- bids/layout/layout.py
- bids/variables/io.py
Attempt to fix problem where is one subject has a `run` defined but another doesn't, then `Analysis.setup()` will crash.
> Fix run is required

- bids/modeling/statsmodels.py
The `Select` transform throws an error when a variable listed in `model.X` is not found in `collection.variables`.
This change retain collection variables directly if in `model.X`.
cc: @effigies
> FIX: Take the intersection of variables and Model.X, ignoring missing variables (usually contrasts)

- bids/cli.py
- bids/layout/validation.py
This command is intended to provide an interactive guide to upgrading a dataset that included features that were part of a BEP to the final versions, once the BEP was finalized and included in BIDS.
The initial use case is fMRIPrep derivatives that predate BIDS 1.4.0. There will surely be others for derivative and raw data.
This is in preparation to enable BIDS 1.4.0 support, especially the transition from `PipelineDescription` to `GeneratedBy`.
> ENH: Add ``pybids upgrade`` command

- .github/workflows/pre-release.yml
- .github/workflows/stable.yml
Looks like I screwed this up when moving to GitHub actions. Apologies.
> MNT: Send codecov reports again

- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/tests/bids_specs.json
- bids/tests/bids_specs_with_oligarchy.json
This line seems to have been forgotten when pathlib was introduced/extended (#746). Without this patch, BIDSLayout is unusable [when specifying `config_filename`](https://github.com/spine-generic/spine-generic/blob/260eafbd2e493382ed0c77517f0cbe18ef27b90f/spinegeneric/cli/params_checker.py#L50-L51) explicitly:
```python
with importlib.resources.path(spinegeneric.config, 'bids_specs.json') as path_sg_layout_config:
layout = BIDSLayout(data_path,indexer=BIDSLayoutIndexer(config_filename=path_sg_layout_config),validate=False)
```
hits
```
File ".../site-packages/bids/layout/models.py", line 156, in load
result = session.query(Config).filter_by(name=config['name']).first()
TypeError: 'PosixPath' object is not subscriptable
```
e.g. https://github.com/spine-generic/data-multi-subject/pull/96/ch …
> Fixup #746

- bids/layout/index.py
- bids/layout/validation.py
We report the failing file to the user if the JSON syntax is bad, but not if there's an invalid Unicode code point.
> FIX: Catch UnicodeDecodeErrors along with JSONDecodeErrors for better reporting

- doc/analysis/index.rst
- doc/layout/index.rst
I noticed that the notebooks in the `examples` directory are not currently linked to the sphinx documentation. This adds a link to each of the notebooks. 
An alternative to this solution would be to convert the notebooks to inputs for sphinx gallery. I see this was raised in the past in https://github.com/bids-standard/pybids/issues/678. 
Another alternative would be to go full jupyter book / myst, which would probably require a bit more work. I could look into that if there is any enthusiasm about that.
> DOC: Link from sphinx documentation to notebook tutorials.

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Mimics `Query.ANY` but allows matching when entity is not present altogether.
See https://github.com/bids-standard/pybids/issues/808
> ENH: Add new `Query` for optional entities

- bids/layout/layout.py
- bids/layout/tests/conftest.py
- bids/layout/tests/test_layout.py
- bids/layout/validation.py
- bids/tests/data/ds005_derivs/format_errs/no_dataset_type/dataset_description.json
- bids/tests/data/ds005_derivs/format_errs/no_pipeline_description/dataset_description.json
Here's my implementation of #804. I couldn't find documentation of autoformatters or code quality checkers, so nothing of that sort has been applied. The changes are summarized below, with some comments following:
BIDSLayout now checks if the root dataset is a derivative by looking for the `DatasetType` entity in `dataset_description.json` to be set to `derivative`. If it is a derivative, the appropriate config (`==['bids', 'derivatives']`) will by used for parsing. No check is made if no valid dataset_description is returned.
If `validate=True`, the derivative dataset is validated using `validate_derivative_paths()`. Bug in `validate_derivative_paths preventing()` the validation of `dataset_description.json` files without either `GeneratedBy` or `PipelineDescription` fields is fixed.
Two …
> Implement automatic detection of derivative data

- bids/ext/__init__.py
> ENH: Add bids.ext namespace package for subpackages

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
~~Haven't looked into our tests to see what needs adjusting/adding.~~
xref https://github.com/poldracklab/fitlins/issues/346 https://github.com/neuroscout/neuroscout/issues/1035
> FIX: Allow grouping by run and session when entities are undefined

- pyproject.toml
- setup.cfg
- setup.py
- tools/ci/env.sh
Jinja2 is breaking everything for everybody. We don't directly depend on it, but nbconvert doesn't have fixes out yet.
Also, it seems setuptools stopped packaging data in 61.0.0.
xref https://github.com/jupyter/nbconvert/pull/1737 https://github.com/pypa/setuptools/issues/3196
> MNT: Avoid jinja2 v3 until nbconvert handles breakages

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
Currently `Query.None` and `Query.ANY` produce unexpected results, such that `get(phase=["mag", None])` to select images that are either explicitly or implicitly magnitude images always returns an empty list.
This PR refactors by:
* Converting all values into a list
* Creating a clause list
* Extracting special queries (NONE, ANY) and adding the the clause list
* Adding additional clauses if there are additional values to match
* Constructing an aggregate OR clause if needed.
Test included. cc @tsalo
Aiming for a 0.14.1 bugfix release so tools can get this without also getting the less obviously-what-you-want #819.
> RF/FIX: Decompose filter construction for special queries and lists

- .mailmap
- .zenodo.json
- CHANGELOG.rst
- tools/prep_zenodo.py
Need #826 without #819, so we need a 0.14.1 release.
Backported some easily-backportable PRs as well.
> REL: 0.14.1

- bids/modeling/statsmodels.py
We've been unable to discern the error cases warned by @tyarkoni's comment about "weird things", so we're going to unleash failure until we come up with some way to discern good from bad. In any event, we should raise an exception if a variable is inappropriate for grouping instead of silently removing variables.
We may be able to identify types of variables (floats?) that would be good candidates for warnings if not errors.
Closes #790.
cc @shashankbansal6
> ENH: Relax group_by rules, allowing any entity to be used

- .gitmodules
- bids/conftest.py
This makes all BIDS examples available to pybids for testing through the `bids_examples` fixture. To enable it, either clone the repository recursively, init/update the submodule, or point to a copy of bids-examples with the `BIDS_EXAMPLES` environment variable.
To use it, write something like:
```Python
def test_ds005(bids_examples):
ds005 = bids_examples / "ds005"
layout = BIDSLayout(ds005)
...
```
We may want to consider a test that fails when the submodule becomes out of sync with `bids-examples:main` (or `:master`... not sure what we're using over there).
cc @Remi-Gau
> TEST: Add bids-examples submodule and bids_examples pytest fixture

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- bids/tests/data/ds005/models/ds-005_type-interceptonlyrunlevel_model.json
Following discussion on 2022-05-06, make intercept only first level models throw a not implemented error
> ENH: Make intercept-only first level models throw a NotImplementedError

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- bids/tests/data/ds005/models/ds-005_type-test_model.json
Addresses: https://github.com/bids-standard/stats-models/issues/40
- Implements renaming these contrasts to prepend the incoming contrast name
- Refactored `DummyContrasts` to simply create Contrasts prior to processing Contrasts. That way, they are processed like any other contrast, and the logic for dealing w/ `1` and other special contrasts is not repeated. 
This might be more controversial but previously the `1` construct would add an intercept named either "intercept" or (in the case of only having one incoming contrast to that Node) the contrast name. Instead, I propose we simply rename the _Contrasts_ if it references the special `1` construct, but always call the intercept "intercept" in the design matrix itself.
I don't feel super strongly about this last bit, but it complicated …
> statsmodels: rename contrasts if they cannot be uniquely identified downstream

- .github/workflows/update_submodules.yml
- .gitmodules
the workflow 
- checks all submodules 
- pull the branch they are tracking
- opens PR on `master` with updated submodules
Added quite a few comments and links in the yml to help with future maintenance but that might be too much. 
To see it in action I merged this in the master of my fork:
- workflow: https://github.com/Remi-Gau/pybids/runs/6916177416?check_suite_focus=true
- PR: https://github.com/Remi-Gau/pybids/pull/2
> [INFRA] add workflow top automatically update submodule

- bids/modeling/tests/test_transformations.py
- bids/modeling/transformations/base.py
- bids/modeling/transformations/compute.py
closes #837 
add:
- ability to output multiple columns from Convolve (orig convolved, derivatives, dispersion)
> [FIX] HRF derivatives as variables

- .github/codespell_exclude_lines.txt
- bids/layout/tests/test_validation.py
- bids/modeling/tests/test_transformations.py
- setup.cfg
Looks like somebody updated their dictionary. They're now catching some intentional misspellings, too, so add an exclude file.
> MNT: Codespell errors

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- bids/tests/data/ds005/models/ds-005_type-test_model.json
Picking up where I left off in #886
First off, I'm changing the tests such that the smoketest runs on the defined model. Previously the `group_by` for each level was set manually rather than respecting what was the `.json` model. 
Second, removing `group_by` contrast, indeed does produce three dummy coded variables (as expected):
However, I don't see where these extra columns would get filtered in the current code. Thus I think the real solution here is to:
- Inject a `intercept` column if defined in X
- Keep track that if there is only a single `contrast`, this `intercept` is effectively that contrast's mean (for convenience, we name the contrast that, instead of `intercept`)
- Filter the DM based on what's in `X`, not simply assuming all other variables are "meta-data"
> Fix filtering of DM columns

- .github/workflows/stable.yml
- bids/modeling/statsmodels.py
- bids/tests/data/ds005/sub-01/sub-01_scans.tsv
- bids/tests/data/ds005/sub-02/sub-02_scans.tsv
- bids/variables/io.py
- bids/variables/tests/test_entities.py
- bids/variables/tests/test_io.py
Proposal for #894.
I added some `scans.tsv` files to ensure that we don't break things when they aren't filtered by level. I also added `scans` to the valid files to load at the subject level, as they can exist there for single-session datasets (like our test dataset). This led to fixing a small bug when filtering scans.tsv variables by run. (We were converting to strings and doing a pattern match. This fails when run is missing, e.g., from T1w files, so the column becomes float, which can't be converted.)
> Accept variable collections at any level

- bids/modeling/tests/test_transformations.py
- bids/modeling/transformations/base.py
There was a small bug where is `sync_kwargs=True` for a transformation, but a non list argument was passed to the Transformation, it would be listified, but to be only lenght 1.
The `sync_kwargs` would later fail, because it's expecting a list of length `variables`.
> Transformations: sync_kwargs, for non-list arguments, listify by variable length

- bids/modeling/statsmodels.py
FIX: Use the correct name for defining `DummyContrasts`: `Conditions`, instead of `ConditionList` or `Conditions`
> Use 'contrasts' in DummyContrasts, not 'condition_list'

- bids/modeling/model_spec.py
- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
- bids/variables/collections.py
- bids/variables/tests/test_collections.py
- bids/variables/tests/test_variables.py
- bids/variables/variables.py
A lot of objects in the `modeling` module lacked `__reprs__` which make building examples for the model zoo more opaque than was necessary.
Examples:
```
<BIDSRunVariableCollection['loss', 'gain', 'RT', 'participant_response']>
<BIDSStatsModelsNode(level=run, name=run)>
<BIDSStatsModelsNodeOutput(level=run, entities={'run': 2, 'subject': '001'})>
<BIDSStatsModelsGraph({name='NARPS', description='NARPS Analysis model', ... })>
<SparseRunVariable(name='loss', source='events')>
```
The general rule I followed is that if more than one item was necessary to identify the object, we would list the argments individual, but in cases like `BIDSVariableCollection` where the most important piece is the name of the variables, I left that as the only "argument".
A particular helpful example is …
> modeling: More helpful __repr__

- bids/modeling/tests/test_transformations.py
- bids/variables/variables.py
Pre-release tests failing.
Pandas has been emitting this warning:
```
FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use
>>> .groupby(..., group_keys=False)
To adopt the future behavior and silence this warning, use 
>>> .groupby(..., group_keys=True)
```
Preserving old behavior fixes the issue. I haven't researched the issue to understand whether we should move to the new behavior and do something else...
> FIX: Address change in default pandas grouping behavior

- setup.cfg
> feat: bump formulaic max version constraint to include 0.5.x

- bids/layout/layout.py
Currently, if the root dataset is a derivative, initializing a `bids.layout.BIDSLayout` object will ignore anything set using `config` as it will always set the config to `["bids", "derivative"]` [as seen here.](https://github.com/bids-standard/pybids/blob/b3351dd25fa74801fa7033ce7e4046382520c461/bids/layout/layout.py#L142)
If a config file path is given to the creation of a `bids.layout.BIDSLayout` object, it should be used - especially in the case of a derivative dataset in which the default derivative BIDS configuration probably does not apply. 
The default `bids` and `derivatives` configurations should only be used if an alternate isn't provided.
Thank you @clin045 for pointing me in the right direction.
> FIX: Allowing custom BIDS configuration files for derivative datasets

- bids/modeling/transformations/compute.py
It looks like newer version of pandas and pybids are having issues with some syntax in the `Scale` and `Convolve` transformations.
In particular, `Scale` has an issue when performing a boolean operation on a Series 
`Convolve` requires the oversampling parameter to be coerced to an `int`
> FIX: Coerce oversampling parameter in convolution to int

- pyproject.toml
Numpy 1.25.0.dev is breaking pre-release Python 3.8. They do not seem to be building wheels. We haven't dropped 3.8 yet (and it seems premature to), so just require numpy 1.24.x or lower for Py3.8.
> MNT: Require numpy 1.24 or lower for Python 3.8

- bids/cli.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/tests/test_layout.py
- bids/layout/validation.py
As indicated in #935, the pattern matching was pretty brittle, and did not take well sophisticated patterns.
This PR converts string matching patterns into regexes (so only one type of pattern is tested, removed that if/else branch of the validation).
This PR makes several decisions that could be controversial:
* When a ``force_index`` or ``ignore``  pattern matches a folder, that's final. This is useful mostly for exclusions: marking a folder for ignore will not try to index any of its contents despite maybe having nested ``force_index``. The speedup in indexing of this decision is huge. If one still wants to have nested force/ignore, please check the new test cases in ``test_layout.py`` showing how to avoid a regex to exactly match the path of a folder (e.g., instead of …
> FIX: Broken pattern matching

- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/tests/test_layout.py
Fixes #940 
The issue is that `BIDSFile.get_entities` is somewhat slow, because it has to do a SQL query. A single query is fine, but in this instance its doing it times the number of files in the result (which with no other argument, is the total number of files indexed).
Instead, I use `BIDSFile.entities`, which is much faster, because its an `association_proxy`. Essentially, instead of doing a complex query that filters, it just pulls all the entities for every file. 
This results in 36x speedup for `get_subjects` in my example dataset (660ms -> 18ms)
The crazy thing is this can be sped up even further, by doing a direct SQL query such as:
```
layout.session.query(models.Tag).filter_by(entity_name='subject').distinct().with_entities(models.Tag._value).all()
```
This only takes 2.14ms, …
> Speed up BIDSLayout.get(return_type='id', ...)

- bids/layout/layout.py
Fixing a bug I introduced in #942 
The problem is that just getting the raw `.entities` variable from a `BIDSFile` will return everything, including meta-data (which is arguably a design flaw). 
The problem if anywhere in the meta-data you use the same name as a BIDS entity (in my case it was `task`), its returns will also be returned. 
This simple fix check if at least the input to `set` is not Hashable, to prevent an error (although it will still return something funky if a non-hashable result from meta-data sneaks in).
> FIX: Exclude non-Hashables from set in .get(return_type='id')

- .mailmap
- .zenodo.json
- CHANGELOG.rst
Been saying this for a couple weeks, but I suppose it's time to actually do a thing.
I don't think anything else can be trivially merged in, so I think we should just go.
@sanjayankur31 @thewilliamdrew @sarthakpati Our scripts have automatically added you as contributors to be cited in Zenodo archives that are auto-generated on releases. If you have ORCIDs or affiliations you would like to add, please make suggestions like:
````
```suggestion
{
"affiliation": "Stanford University",
"name": "Markiewicz, Christopher J.",
"orcid": "0000-0002-6533-164X"
},
```
````
If you would prefer *not* to be cited as a contributor, then we can add you to a blacklist to prevent scripts from re-adding you.
> REL: 0.15.6

- .github/workflows/package.yml
```
Input 'repository_url' has been deprecated with message: The inputs have been normalized to use kebab-case. Use `repository-url` instead.
Input 'skip_existing' has been deprecated with message: The inputs have been normalized to use kebab-case. Use `skip-existing` instead.
```
See https://github.com/pypa/gh-action-pypi-publish/pull/125.
> CI: Update parameters to gh-action-pypi-publish

- bids/layout/tests/test_layout_on_examples.py
Before https://github.com/bids-standard/bids-examples/commit/36ab2fffc3da7f17bb9df02a9fcbe00ff019a1a0 / https://github.com/bids-standard/bids-examples/pull/337:
```sh
$ find qmri_irt1 -type f | wc -l
16
$ 
$ find qmri_mp2rage -type f | wc -l
15
$ 
$ find qmri_mtsat -type f | wc -l
24
$ 
$ find qmri_megre -type f | wc -l
18
$ 
$ find qmri_vfa -type f | wc -l
18
$ 
```
After https://github.com/bids-standard/bids-examples/commit/36ab2fffc3da7f17bb9df02a9fcbe00ff019a1a0 / https://github.com/bids-standard/bids-examples/pull/337:
```sh
$ find qmri_irt1 -type f | wc -l
17
$ 
$ find qmri_mp2rage -type f | wc -l
16
$ 
$ find qmri_mtsat -type f | wc -l
26
$ 
$ find qmri_megre -type f | wc -l
19
$ 
$ find qmri_vfa -type f | wc -l
19
$ 
```
> CI: fix errors caused by changes in examples

- bids/variables/variables.py
Various improvements to increase the speed of converting Sparse to Dense variables by an order of magnitude.
The previous approach was to:
1) First upsample the variable (potentially really high if the events have high temporal frequency)
2) Create an upsampled `DenseRunVariable`
3) resample to the desired (e.g. TR) sampling rate
The issue is that `DenseRunVariable.__init__` is somewhat slow. And much of what is done in `__init__` (bulding index) gets redone upon resample. 
I made several improvements to `__init__`, but in the end what was most imapctful was to abstract out the resampling logic, and apply it directly to the upsampled timecourse prior to creating a `DenseRunVariable`. Thus, once `DenseRunVariable.__init__` is run, it's on lower frequency data, and thus much faster.
For me, …
> BIDSVariables: Speed up Sparse to Dense

- .github/workflows/stable.yml
- pyproject.toml
Following NEP 29, dropping Python 3.7 support
> Drop Python 3.7 EOL

- bids/modeling/report/utils.py
- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
For VIF calculation, we can't have any zeros in the DM
I propose filling them with zeros.
I believe this is equivalent to what happens in the long run in FitLins.
Alternatively, we could fill them with zero's more explicitly elsewhere in the process.
> FIX: Fill na with zero for VIF

- bids/modeling/statsmodels.py
- bids/modeling/tests/test_statsmodels.py
@effigies Sorry, but I thought of this after merging.
We should only warn if `missing_values` becomes `fill` because the user did not explicitly set it, otherwise we should stay silent.
If not, there's a lot of busy warnings even if filling in NaN with `0` is what you explicitly want.
> ENH: Only warn if missing values not explicilty set

- pyproject.toml
> MNT: Drop jinja2/markupsafe constraints

- bids/layout/models.py
- bids/layout/tests/test_models.py
- bids/layout/tests/test_writing.py
- pyproject.toml
Looking at https://github.com/executablebooks/jupyter-cache/pull/93 (thanks for finding, @DimitriPapadopoulos!), our sqlalchemy issues may have been smaller than they seemed they were going to be. Let's see.
Closes #680.
> FIX: Adapt to SQLAlchemy 1.4+

- .zenodo.json
- CHANGELOG.rst
- tools/prep_zenodo.py
#994 and #997 justify a quick bug-fix release, IMO.
@pvandyken Do you still prefer not to be listed as a contributor?
> REL: 0.16.1

- .github/workflows/package.yml
Giving https://docs.pypi.org/trusted-publishers/ a try. Since we push to test.pypi.org, this is a good package to try it on.
> CI: Use OIDC publishing instead of tokens

- bids/layout/layout.py
Small bug fix which passes the indexer object into add_derivatives along with indexer kwargs.
Previously, index options could only be included in derivative datasets with index kwargs, which are deprecated.
This includes the indexer object in derivative BIDSLayout instantiation.
closes #970
> Include indexer in add_derivatives call

- CHANGELOG.rst
Bug-fix and performance release in the 0.16.x series.
Notably, indexing is now significantly faster (2-2.5x).
> REL: 0.6.2

- bids/layout/index.py
- bids/tests/data/ds005/task-mixedgamblestask_bold.json
Starting by reproducing #1015.
Either need to encode `None`s as JSON `null`s or skip adding tags for them. My inclination is skip.
Fixes #1015.
> FIX: Drop JSON sidecar fields with null values during metadata indexing

- bids/layout/models.py
- bids/layout/tests/test_layout.py
- bids/tests/data/7t_trt/task-rest_acq-fullbrain_bold.json
Closes #1033. As @effigies suspected, the problem stems from the fact that metadata fields are initially converted to strings (`False` becomes `'False'`) and _then_ are converted using the desired datatype (`bool('False')` becomes `True`).
Changes proposed:
1. Add a boolean metadata field to one of the test datasets with a value of False. I chose `MTState` in the 7t_trt dataset since that dataset is used in `test_get_metadata`.
2. Add a test, `test_get_metadata_error2`, that checks that the value returned is False.
3. Check for boolean datatypes in `Tag._init_on_load()` and explicitly convert `'False'` to `False`. Other datatypes and values can be handled using the old code.
> FIX: Ensure values of boolean metadata fields are preserved

- .zenodo.json
- CHANGELOG.rst
Bug-fix release in the 0.16.x series.
This release resolves a bug likely introduced in 0.9.0 (when PyBIDS started using SQL), in which boolean metadata fields with values of `False` were read in as `True`.
> REL: 0.16.4

- bids/reports/report.py
- bids/variables/variables.py
- doc/analysis/index.rst
- doc/api.rst
- doc/conf.py
- doc/examples/statsmodels_tutorial.md
- doc/includes/big_toc_css.rst
- doc/includes/bigger_toc_css.rst
- doc/layout/index.rst
- doc/tune_toc.rst
- pyproject.toml
- closes none but related to https://github.com/bids-standard/pybids/pull/1055#pullrequestreview-2039309358
> [DOC] deal with several warnings and errors in the doc build

- .github/workflows/test.yml
- bids/modeling/report/base.py
- bids/variables/variables.py
Builds on #1055, fixes one small bug and removes an import of the deprecated (and removed from default installations) `pkg_resources`.
> MNT: Add Python 3.12 support

- .github/workflows/package.yml
- .mailmap
- .zenodo.json
- CHANGELOG.rst
Release prep for 0.16.5. As indicated by the patch increment, I think the changes over 0.16.5 (https://github.com/bids-standard/pybids/compare/0.16.4...rel/0.16.5) are minimal, but they have accumulated.
@bpinsard @akhanf @alperkent I've added you to the Zenodo file, so you will be credited as authors in this and future releases. If you would prefer not to be let me know. If you would like to add ORCIDs or affiliations, let me know.
With sign-off, I'll release today. Without sign-off or objection, I'll release tomorrow.
> REL: 0.16.5

- bids/config.py
- bids/conftest.py
- bids/layout/db.py
- bids/layout/index.py
- bids/layout/layout.py
- bids/layout/models.py
- bids/layout/utils.py
- bids/layout/validation.py
- bids/layout/writing.py
- bids/utils.py
- pyproject.toml
- setup.py
This PR makes a relatively small change to the code that enables pybids to parse any filesystem backend that is supported by universal_pathlib (which is a subset of those supported by fsspec), by dropping in UPath instead of Path.
The list of filesystems currently supported (from https://github.com/fsspec/universal_pathlib) is:
- `file:` Local filesystem
- `memory:` Ephemeral filesystem in RAM
- `az:`, `adl:`, `abfs:` and `abfss:` Azure Storage _(requires `adlfs`)_
- `data:` RFC 2397 style data URLs _(requires `fsspec>=2023.12.2`)_
- `github:` GitHub repository filesystem
- `http:` and `https:` HTTP(S)-based filesystem
- `hdfs:` Hadoop distributed filesystem
- `gs:` and `gcs:` Google Cloud Storage _(requires `gcsfs`)_
- `s3:` and `s3a:` AWS S3 _(requires `s3fs` to be installed)_
- …
> ENH: pathlib -> universal_pathlib to enable cloud (and other filesystem) support

- bids/modeling/transformations/munge.py
- bids/variables/collections.py
- bids/variables/io.py
- bids/variables/variables.py
Pandas is currently generating `FutureWarning`s:
```
.../.venv/lib/python3.12/site-packages/bids/variables/variables.py:535: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
df.iloc[prev_ix:prev_ix + reps, col_ix] = v
```
https://github.com/bids-standard/pybids/blob/03a1af5af925a62e2a036d70b80d32e25066fca4/bids/variables/variables.py#L527-L538
Debugging, the issue is that we're creating the dataframe with a `np.zeros()`, so `dtype=float`, but entities and metadata may be strings, lists, etc. Using `dtype=object` resolves this.
> fix: Create indices with object dtype

- bids/layout/index.py
- bids/layout/tests/test_layout.py
> BUG: symlink dirs treated as files during indexing

- bids/layout/index.py
- bids/layout/tests/test_remote_bids.py
- pyproject.toml
- setup.py
The _check_path_matches_patterns function was failing for cloud (e.g. s3, gc3) URIs (added in #1074):
1) the path.relative_to() function doesn't work for cloud URIs
(it just returns the original).
2) combining Path('/') with the result of relative_to() now (ie since universal_pathlib > 0.2.3) throws
an error when using cloud paths. 
So if using universal_pathlib >0.2.3, any cloud URIs as bids datasets would throw an error message.
This fix drops the uri prefix by using .path, so that the regex check works as expected.
> FIX: cloud paths checking against patterns

- src/bids/reports/parameters.py
- src/bids/reports/parsing.py
- src/bids/reports/utils.py
This PR removes the calls to `logging.basicConfig` in the reports module, addressing #1105
> Remove calls to root logger basicConfig

- bids/layout/layout.py
- bids/layout/tests/test_layout.py
- bids/utils.py
- setup.cfg
> FIX: Make lists and dicts hashable

- .github/workflows/build-test-deploy.yml
- pyproject.toml
- tox.ini
This PR does the following:
* Adopts tox-uv as a speedup for constructing test environments and automatically calculating minimum versions.
* This requires setting lower bounds on test dependencies, which is fine. We don't need to be very conservative with these. I just picked some that have worked with other projects I've updated recently and the most recent major versions of some others.
* ~~Adds the scipy nightly build package index so we'll see breakage coming with plenty of warning.~~ Deferred.
* Begins testing on 3.13, which is enabled because altair released a new minor version. This cherry-picks @Remi-Gau's #1093.
* Some cleanups to coverage. I added tests/ to coverage, even though it's currently only data, so that they'll get picked up if we ever add tests that we don't want …
> chore: Use tox-uv to ease lower bound checking, test on Python 3.13

- src/bids/layout/config/bids.json
- src/bids/layout/config/derivatives.json
Related to https://github.com/bids-standard/bids-specification/pull/1926.
Changes proposed:
- Add `+` signs to the regular expressions for label entities in the `bids` and `derivatives` config files.
> ENH: Allow plus signs in labels

- src/bids/layout/tests/test_utils.py
- src/bids/layout/utils.py
If an exception is raised by `val == self.sval or ...` (that is, `val.__eq__(self.sval).__bool__()`), we defer to the `val` type to determine the correct behavior. This is currently only expected to be triggered by array-like types, but any type that goes this far out of its way to change its boolean behavior is one we don't want to get too fancy with.
In the spirit of not getting fancy, we drop any consideration of the padded string in this context.
> fix: Allow numpy arrays to treat PaddedInt like int

- src/bids/modeling/tests/test_statsmodels.py
- src/bids/variables/io.py
This resolves a very particular bug, which may or may not be the last, related to losing the zero-padding when processing a dataset with fitlins.
It turns out that once you call `BIDSStatsModelsGraph.load_collections()`, you lose the `PaddedInt` type in the BIDSFile's entity dictionary. This is because we mutate the dictionary in-place. This PR copies the dict and improves the comments.
Starting with a test I can confirm failed before the fix was applied.
> fix: Copy entities dict before modifying run variable type

- src/bids/layout/tests/conftest.py
- src/bids/layout/tests/test_layout.py
- src/bids/layout/validation.py
Dotfiles are ignored by default, but custom ignore patterns override the default ignores. This change ensures that dotfiles are always ignored in either case.
Regression test reproduces #1069 and patch fixes it.
Closes #1069.
> fix: Ensure dotfiles are always filtered

- src/bids/layout/index.py
We're occasionally getting failures like https://github.com/bids-standard/pybids/actions/runs/13679431654/job/38247759389
```
=================================== FAILURES ===================================
_________________________ test_layout_with_validation __________________________
[gw1] linux -- Python 3.11.11 /home/runner/work/pybids/pybids/.tox/py311-pre/bin/python3
def test_layout_with_validation():
data_dir = join(get_test_data_path(), '7t_trt')
layout1 = BIDSLayout(data_dir, validate=True)
>       layout2 = BIDSLayout(data_dir, validate=False)
src/bids/layout/tests/test_validation.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/bids/layout/layout.py:177: in __init__
_indexer(self)
src/bids/layout/index.py:153: in __call__
all_bfs, …
```
> fix: Catch StopIteration on directory walk
